import React,{useMemo,useState}from'react';import'../styles/sponsor.css';
const CAR='https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CarConcept/screenshot/screenshot.png';
const zones=[
{id:'hood',name:'Hood',price:175000,bids:0,tier:'Anchor',vis:'Front + content hero',x:'48%',y:'48%'},
{id:'driver-door',name:'Driver Door',price:155000,bids:0,tier:'Flagship',vis:'Side profile + rolling shots',x:'41%',y:'60%'},
{id:'passenger-door',name:'Passenger Door',price:155000,bids:0,tier:'Flagship',vis:'Side profile + rolling shots',x:'60%',y:'60%'},
{id:'wing',name:'Rear Wing',price:135000,bids:0,tier:'Signature',vis:'Iconic detail + rear angles',x:'79%',y:'35%'},
{id:'rear-quarter',name:'Rear Quarter',price:120000,bids:0,tier:'Premium',vis:'Motion + tracking content',x:'69%',y:'55%'},
{id:'roof',name:'Roof',price:105000,bids:0,tier:'Drone',vis:'Overhead + event footage',x:'53%',y:'34%'},
{id:'front-bumper',name:'Front Bumper',price:95000,bids:0,tier:'Core',vis:'Arrival + front angles',x:'23%',y:'63%'},
{id:'rear-bumper',name:'Rear Bumper',price:95000,bids:0,tier:'Core',vis:'Follow + departure shots',x:'84%',y:'63%'}];
const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n);
export function SponsorExperience(){
const[selected,setSelected]=useState(zones[0]);const[brand,setBrand]=useState('YOUR BRAND');const[accent,setAccent]=useState('#10d9ff');const[modal,setModal]=useState(false);const[form,setForm]=useState({name:'',email:'',company:'',website:'',budget:'',note:''});const[sent,setSent]=useState(false);
const target=1344000,vehicle=500000,modelCosts=640000,surplus=650000,raised=0;const avg=Math.round(target/zones.length);
const zoneTotal=useMemo(()=>zones.reduce((a,z)=>a+z.price,0),[]);
const submit=async e=>{e.preventDefault();setSent(false);const concept=['GT3 sponsorship',selected.name,selected.tier,selected.vis,'Website: '+(form.website||'not provided'),'Budget CAD: '+(form.budget||'not provided'),'Note: '+(form.note||'none')].join(' | ');try{const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.email,segment:'brands',name:form.name,audience:form.company,concept,outcome:'BrainSNN GT3 sponsorship review',timeline:'Launch campaign'})});const data=await res.json().catch(()=>({}));if(!res.ok){const fallback=data.fallbackEmail||'hello@brainsnn.com';window.location.href='mailto:'+fallback+'?subject='+encodeURIComponent('BrainSNN GT3 sponsor proposal - '+form.company)+'&body='+encodeURIComponent(concept+'\\n\\nName: '+form.name+'\\nEmail: '+form.email);return}setSent(true)}catch{window.location.href='mailto:hello@brainsnn.com?subject='+encodeURIComponent('BrainSNN GT3 sponsor proposal - '+form.company)+'&body='+encodeURIComponent(concept+'\\n\\nName: '+form.name+'\\nEmail: '+form.email)}};
return <div className="sponsor-page">
<header className="sponsor-nav"><div className="sponsor-wrap sponsor-nav-in"><a className="sponsor-brand" href="/sponsor">Brain<b>SNN</b><small>by XIO</small></a><nav className="sponsor-links"><a href="#why">Why Sponsor</a><a href="#zones">Ad Zones</a><a href="#funding">Funding</a><a href="#fleet">The Fleet</a><a href="#faq">FAQ</a></nav><button className="sponsor-btn primary" onClick={()=>setModal(true)}>Partner With Us →</button></div></header>
<main>
<section className="sponsor-wrap sponsor-hero"><div><div className="sponsor-kicker">REAL AI · REAL WORLD REACH · MEASURABLE CAMPAIGNS</div><h1>PUT YOUR BRAND<br/>ON THE <span className="sponsor-gradient">FUTURE.</span></h1><p className="sponsor-lead">The BrainSNN GT3 Experiment turns a high-attention physical asset into a measurable sponsor campaign. Pick a placement, preview your brand, propose a partnership, and follow the results.</p><div className="sponsor-actions"><button className="sponsor-btn primary" onClick={()=>document.querySelector('#zones')?.scrollIntoView({behavior:'smooth'})}>Explore Sponsorship Spots →</button><button className="sponsor-btn" onClick={()=>document.querySelector('#funding')?.scrollIntoView({behavior:'smooth'})}>See Funding Model</button></div><div className="sponsor-stats"><div className="sponsor-stat"><strong>8</strong><span>Launch zones</span></div><div className="sponsor-stat"><strong>CAD</strong><span>Transparent pricing</span></div><div className="sponsor-stat"><strong>1</strong><span>Measurable campaign</span></div></div></div>
<div className="sponsor-stage"><img className="sponsor-car" src={CAR} alt="Interactive concept car used to preview BrainSNN sponsorship placements"/>{zones.map((z,i)=><button key={z.id} className={'sponsor-hotspot '+(selected.id===z.id?'active':'')} style={{left:z.x,top:z.y}} onClick={()=>setSelected(z)} aria-label={'Select '+z.name}>{i+1}</button>)}</div></section>
<section id="zones" className="sponsor-wrap sponsor-section"><div className="sponsor-section-head"><div><div className="sponsor-kicker">01 · SPONSORSHIP PLAYGROUND</div><h2>Choose a zone. Make it yours.</h2></div><p className="sponsor-muted">Prices are launch-model floors, not evidence of sponsor demand. Final placement and campaign terms are agreed before payment.</p></div><div className="sponsor-grid"><div className="sponsor-card"><div className="sponsor-zone-list">{zones.map((z,i)=><button key={z.id} className={'sponsor-zone '+(selected.id===z.id?'active':'')} onClick={()=>setSelected(z)}><span className="sponsor-zone-index">{String(i+1).padStart(2,'0')}</span><span><strong>{z.name}</strong><small>{z.vis}</small></span><span className="sponsor-zone-price">{money(z.price)}</span><span className="sponsor-live">AVAILABLE</span></button>)}</div></div><aside className="sponsor-card"><div className="sponsor-kicker">SELECTED ZONE</div><h2>{selected.name}</h2><p className="sponsor-muted">{selected.vis}. Designed for a premium but coherent livery, not a wall of stickers.</p><div className="sponsor-detail-price">{money(selected.price)}</div><div className="sponsor-muted">Illustrative sponsorship floor · before applicable tax</div><div className="sponsor-detail-grid"><div className="sponsor-mini"><span>Tier</span><strong>{selected.tier}</strong></div><div className="sponsor-mini"><span>Bids</span><strong>{selected.bids}</strong></div><div className="sponsor-mini"><span>Status</span><strong>Open</strong></div></div><button className="sponsor-btn primary" style={{width:'100%'}} onClick={()=>setModal(true)}>Propose this placement →</button></aside></div></section>
<section className="sponsor-wrap sponsor-section"><div className="sponsor-section-head"><div><div className="sponsor-kicker">02 · CUSTOMIZE + PREVIEW</div><h2>See your name in the campaign.</h2></div></div><div className="sponsor-custom"><div className="sponsor-card"><div className="sponsor-field"><label>Brand name</label><input maxLength="28" value={brand} onChange={e=>setBrand(e.target.value.toUpperCase())}/></div><div className="sponsor-field"><label>Accent</label><div className="sponsor-swatches">{['#10d9ff','#875cff','#ff4db8','#22d3a3','#f5a623'].map(c=><button key={c} className="sponsor-swatch" style={{background:c,outline:accent===c?'2px solid white':'none'}} onClick={()=>setAccent(c)}/>)}</div></div><p className="sponsor-muted">A production version can project uploaded sponsor artwork directly onto a licensed 3D GT3 texture. This preview keeps the interaction lightweight until that asset is licensed.</p></div><div className="sponsor-preview" style={{boxShadow:'inset 0 0 70px '+accent+'22'}}><img src={CAR} alt="Sponsor preview car"/><div className="sponsor-logo-chip" style={{borderColor:accent,boxShadow:'0 0 24px '+accent+'55'}}>{brand||'YOUR BRAND'}</div></div></div></section>
<section id="funding" className="sponsor-wrap sponsor-section"><div className="sponsor-section-head"><div><div className="sponsor-kicker">03 · FUNDING MODEL</div><h2>The campaign earns the green light.</h2></div></div><div className="sponsor-funding"><div className="sponsor-card"><div className="sponsor-detail-price">{money(target)}</div><p className="sponsor-muted">Modelled sponsorship revenue threshold before sales tax. It covers the illustrative vehicle budget, campaign costs, fees and a cash-surplus goal equal to 130% of the vehicle budget.</p><div className="sponsor-progress"><span style={{width:(raised/target*100)+'%'}}/></div><div style={{display:'flex',justifyContent:'space-between'}}><b>{money(raised)} verified paid</b><span className="sponsor-muted">0% funded</span></div></div><div className="sponsor-card sponsor-kpis"><div className="sponsor-kpi"><span>Vehicle budget</span><strong>{money(vehicle)}</strong></div><div className="sponsor-kpi"><span>Modelled costs</span><strong>{money(modelCosts)}</strong></div><div className="sponsor-kpi"><span>Requested surplus</span><strong>{money(surplus)}</strong></div><div className="sponsor-kpi"><span>Avg / 8 zones</span><strong>{money(avg)}</strong></div></div></div><p className="sponsor-ref">The eight displayed zone floors currently total {money(zoneTotal)}. They are editable commercial assumptions, not collected revenue or guaranteed profit.</p></section>
<section id="why" className="sponsor-wrap sponsor-section"><div className="sponsor-section-head"><div><div className="sponsor-kicker">04 · WHY SPONSOR BRAINSNN?</div><h2>More than a logo.</h2></div></div><div className="sponsor-benefits"><div className="sponsor-benefit"><span>◉</span><b>Real-world visibility</b><p>Physical placement plus campaign content in agreed locations and events.</p></div><div className="sponsor-benefit"><span>▣</span><b>Content creation</b><p>Professional campaign assets and a shared creative direction.</p></div><div className="sponsor-benefit"><span>▥</span><b>Measurable interactions</b><p>Track agreed views, scans, clicks and attributable inquiries.</p></div><div className="sponsor-benefit"><span>◎</span><b>BrainSNN experiment</b><p>Test a message or workflow, record the hypothesis, then report what happened.</p></div></div></section>
<section id="fleet" className="sponsor-wrap sponsor-section"><div className="sponsor-section-head"><div><div className="sponsor-kicker">05 · THE FLEET</div><h2>One experiment first. Expand on evidence.</h2></div></div><div className="sponsor-fleet"><div className="sponsor-fleet-item live"><b>#001<br/>GT3 EXPERIMENT<br/><span className="sponsor-live">PRELAUNCH</span></b></div>{[2,3,4,5].map(n=><div className="sponsor-fleet-item" key={n}><b>#{String(n).padStart(3,'0')}<br/>COMING SOON</b></div>)}</div></section>
<section id="faq" className="sponsor-wrap sponsor-section sponsor-faq"><div className="sponsor-kicker">FAQ</div><h2>Clear before you commit.</h2><details><summary>Is this a live auction?</summary><p>Not yet. The public page is a sponsorship marketplace preview. A submitted proposal is not a bid, reservation or payment.</p></details><details><summary>What happens after I apply?</summary><p>XIO reviews brand fit, placement, scope, campaign dates and commercial terms. Approved sponsors receive a defined agreement and a secure Stripe checkout invitation.</p></details><details><summary>Is the GT3 already purchased?</summary><p>No claim is made here that the vehicle is acquired. Vehicle access, insurance and campaign terms must be confirmed before payment collection opens.</p></details><details><summary>Are results guaranteed?</summary><p>No. Campaign reporting should separate measured reach and attributable inquiries from projections. BrainSNN analysis is directional, not literal neurological measurement.</p></details><div className="sponsor-cta"><div><div className="sponsor-kicker">LIMITED LAUNCH INVENTORY</div><h2>Build the first BrainSNN physical campaign with us.</h2></div><button className="sponsor-btn primary" onClick={()=>setModal(true)}>Explore Sponsorship Spots →</button></div></section>
</main><footer className="sponsor-footer"><div className="sponsor-wrap"><b>BrainSNN by XIO</b><div>REAL INTELLIGENCE · REAL CONNECTIONS · REAL IMPACT.</div></div></footer>
{modal&&<div className="sponsor-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="sponsor-modal-card" onSubmit={submit}><div className="sponsor-modal-head"><div><div className="sponsor-kicker">SPONSOR APPLICATION</div><h2>{selected.name} · {money(selected.price)}</h2></div><button type="button" className="sponsor-close" onClick={()=>setModal(false)}>✕</button></div>{sent?<div className="sponsor-success">Proposal received by BrainSNN for review. This is not a confirmed sponsorship or payment.</div>:<><div className="sponsor-form-grid"><div className="sponsor-field"><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="sponsor-field"><label>Company</label><input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></div></div><div className="sponsor-field"><label>Email</label><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="sponsor-field"><label>Website</label><input type="url" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><div className="sponsor-field"><label>Proposed budget, CAD</label><input required type="number" min="0" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></div><div className="sponsor-field"><label>What do you want to demonstrate?</label><textarea rows="4" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><button className="sponsor-btn primary" style={{width:'100%'}} type="submit">Send sponsor proposal →</button><p className="sponsor-notice">No card is collected here. Applications are non-binding. Approved sponsors can be sent to Stripe-hosted checkout only after campaign launch conditions are satisfied.</p></>}</form></div>}
</div>}