import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';

const root = path.resolve('sponsorship');
const out = path.join(root, 'reports');
await fs.mkdir(out, {recursive:true});
const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'sponsor-handoff-'));
const base = 'http://127.0.0.1:8093';
const server = spawn(process.execPath, [path.join(root,'server.cjs')], {env:{...process.env,NODE_ENV:'test',PORT:'8093',SPONSOR_PUBLIC_ORIGIN:base,SPONSOR_DB_PATH:path.join(temp,'isolated.sqlite'),SPONSOR_PAYMENTS_ENABLED:'false'},stdio:['ignore','pipe','pipe']});
let logs = ''; server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
const evidence = {base,isolatedDatabase:true,productionWrites:0,paymentsEnabled:false,checks:[]};
let browser;
try {
  let ready=false;
  for(let i=0;i<60;i++){try{if((await fetch(base+'/api/sponsors/status')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,250));}
  assert.ok(ready,logs);
  browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:base});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/sponsor/?placement=back#studio',{waitUntil:'networkidle',timeout:120000});
  await page.waitForSelector('#studio-robot[data-ready="true"]',{timeout:120000});
  assert.equal(await page.locator('#placement-name').textContent(),'Back');
  assert.equal(await page.locator('[data-view=back]').getAttribute('aria-pressed'),'true');
  assert.equal((await page.locator('#opening-price').textContent()).replace(/[^0-9]/g,''),'5000');
  await page.locator('#brand-text').fill('PRIVATE PREVIEW');
  await page.locator('#share-placement').click();
  await page.waitForFunction(()=>document.getElementById('share-placement-status').textContent.includes('copied'));
  const link=await page.evaluate(()=>navigator.clipboard.readText());
  assert.equal(link,'https://www.brainsnn.com/sponsor/?placement=back#studio');
  assert.ok(!link.includes('PRIVATE'));evidence.checks.push('Back deep-link selects real price/view; copied URL shares only placement.');
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Clipboard denied for isolated test');}}}));
  await page.locator('#share-placement').click();
  await page.locator('#placement-share-link').waitFor({state:'visible'});
  assert.equal(await page.locator('#placement-share-link').inputValue(),link);
  await page.locator('.showroom').screenshot({path:path.join(out,'launch-share.png')});
  evidence.checks.push('Clipboard-denied fallback reveals selectable link.');
  await page.locator('#offer-button').click();
  await page.locator('[name=name]').fill('Isolated QA');await page.locator('[name=company]').fill('Example Launch Test');await page.locator('[name=email]').fill('qa@example.com');await page.locator('[name=campaign]').fill('Isolated browser verification only. Not a real sponsor or production application.');await page.locator('[name=privacyConsent]').check();
  const response=page.waitForResponse(r=>r.url()===base+'/api/sponsors/applications'&&r.request().method()==='POST');
  await page.locator('#submit-application').click();assert.equal((await response).status(),201);
  await page.waitForFunction(()=>!document.getElementById('download-application-confirmation').disabled);
  const reference=await page.locator('#application-reference').inputValue();
  const downloading=page.waitForEvent('download');await page.locator('#download-application-confirmation').click();const download=await downloading;
  const text=await fs.readFile(await download.path(),'utf8');
  assert.ok(text.includes(reference));assert.ok(text.includes('Example Launch Test'));assert.ok(text.includes('C$5,000.00'));assert.ok(text.includes('not an invoice'));assert.ok(!text.includes('PRIVATE PREVIEW'));assert.ok(!text.includes('qa@example.com'));
  await page.locator('#copy-application-reference').click();
  assert.ok((await page.locator('#confirmation-status').textContent()).includes('copy the application reference'));
  await page.locator('#application-dialog').screenshot({path:path.join(out,'launch-confirmation.png')});
  evidence.checks.push('Actual isolated POST returned201; saved confirmation matches reference and proposal; no private artwork/email leaked.');
  await page.locator('#done-dialog').click();
  await page.locator('#offer-button').click();
  await page.locator('[name=name]').fill('Isolated QA');await page.locator('[name=company]').fill('Failed Test');await page.locator('[name=email]').fill('qa@example.com');await page.locator('[name=campaign]').fill('Isolated failure path test. This must not create a real confirmation.');await page.locator('[name=privacyConsent]').check();
  await page.route('**/api/sponsors/applications',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Isolated unavailable test'})}));
  await page.locator('#submit-application').click();await page.locator('#form-error:not([hidden])').waitFor();
  assert.equal(await page.locator('#application-success').isVisible(),false);assert.equal(await page.locator('#download-application-confirmation').isEnabled(),false);
  evidence.checks.push('Failed POST does not reveal success or enable a confirmation.');
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+'/sponsor/?placement=unknown#studio',{waitUntil:'networkidle',timeout:120000});
  await page.locator('#share-placement:enabled').waitFor();assert.equal(await page.locator('#placement-name').textContent(),'Chest');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('.showroom').screenshot({path:path.join(out,'launch-mobile.png')});
  assert.equal(errors.length,0,errors.join('; '));
  evidence.checks.push('Unknown placement safely falls back to Chest on mobile; no horizontal overflow or browser errors.');
  evidence.ok=true;
} catch(error){evidence.ok=false;evidence.error=error.stack;process.exitCode=1;}
finally{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(r=>setTimeout(r,200));await fs.rm(temp,{recursive:true,force:true});await fs.writeFile(path.join(out,'launch-evidence.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));}
