'use strict';
process.env.GT3_SKIP_PRELOAD='true';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http'),zlib=require('node:zlib');
const {createHandler}=require('../server.cjs');const {validateOrder}=require('../commerce.cjs');
function crc(b){let n=0xffffffff;for(const v of b){n^=v;for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;}return (n^0xffffffff)>>>0;}
function png(){const chunk=(t,b)=>{const a=Buffer.alloc(12+b.length);a.writeUInt32BE(b.length);a.write(t,4);b.copy(a,8);a.writeUInt32BE(crc(a.subarray(4,8+b.length)),8+b.length);return a;},h=Buffer.alloc(13);h.writeUInt32BE(512);h.writeUInt32BE(256,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',h),chunk('IDAT',zlib.deflateSync(Buffer.alloc(524544))),chunk('IEND',Buffer.alloc(0))]).toString('base64');}
const image=png(),product='brainsnn_gt3_sponsorship_2026';
function body(){return {requestId:crypto.randomUUID(),name:'Test Sponsor',company:'QA fixture',email:'qa@example.test',zone:'driver-door',brand:'QA',scale:1,png:image,consent:true};}
function fixture(){const sessions=new Map(),keys=new Map(),calls=[];
 const fake={accounts:{retrieve:async()=>({id:'acct_1Sx9KTE2zpmvdOtT',charges_enabled:true})},products:{retrieve:async()=>({id:product,active:true,livemode:false,tax_code:'test-only-reviewed-code'})},tax:{settings:{retrieve:async()=>({status:'active',head_office:{address:{country:'CA'}}})},registrations:{list:async()=>({data:[{country:'CA',status:'active'}]})}},checkout:{sessions:{create:async(p,options)=>{calls.push({p,options});if(keys.has(options.idempotencyKey))return sessions.get(keys.get(options.idempotencyKey));const id='cs_test_'+crypto.randomBytes(12).toString('hex'),price=p.line_items[0].price_data;const s={id,url:'https://checkout.stripe.com/c/pay/'+id,livemode:false,status:'open',payment_status:'unpaid',mode:'payment',currency:'cad',metadata:p.metadata,amount_subtotal:price.unit_amount,amount_total:Math.round(price.unit_amount*1.13),line_items:{data:[{quantity:1,price:{...price}}],has_more:false},total_details:{amount_discount:0},automatic_tax:{enabled:true,status:'complete'},payment_intent:null};sessions.set(id,s);keys.set(options.idempotencyKey,id);return s;},retrieve:async id=>{const s=sessions.get(id);if(!s)throw Error('No session');return s;}}}};
 const env={NODE_ENV:'test',GT3_STRIPE_MODE:'test',GT3_PAYMENTS_ENABLED:'true',GT3_STRIPE_WEBHOOK_SECRET:crypto.randomBytes(32).toString('hex'),SPONSOR_SESSION_SECRET:crypto.randomBytes(32).toString('hex'),SPONSOR_ADMIN_KEY:crypto.randomBytes(32).toString('hex'),GT3_CAMPAIGN_JSON:JSON.stringify({approved:true,version:'test-fixture-v1',merchant:'Test merchant',businessAddress:'Test fixture address',starts:new Date(Date.now()+86400000).toISOString(),ends:new Date(Date.now()+90*86400000).toISOString(),deliverables:'Fixture only, not a real offer',refundPolicy:'Fixture only refund terms',fundingPolicy:'Fixture only funding terms'})};
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gt3-commerce-')),options={env,stripe:fake,dbPath:path.join(dir,'orders.sqlite'),origin:'http://localhost'};const h=createHandler(options),c=h.commerce;
 const paid=id=>{const s=sessions.get(id);s.status='complete';s.payment_status='paid';s.payment_intent={id:'pi_'+id,status:'succeeded',currency:'cad',amount_received:s.amount_total,latest_charge:{id:'ch_'+id,paid:true,refunded:false,disputed:false,amount_refunded:0}};return s;};
 return {h,c,options,env,fake,sessions,calls,paid,close(){h.close();fs.rmSync(dir,{recursive:true,force:true});}};
}
test('normalized PNG preview and validated contact fields only',()=>{const b=body(),v=validateOrder({...b,amount:1,paid:true});assert(v.amount>1);assert(!Object.hasOwn(v,'paid'));assert.equal(v.image.readUInt32BE(16),512);assert.throws(()=>validateOrder({...b,consent:false}));assert.throws(()=>validateOrder({...b,png:Buffer.from('<svg onload=alert(1)>').toString('base64')}));assert.throws(()=>validateOrder({...b,zone:'chest'}));assert.throws(()=>validateOrder({...b,scale:99}));});
test('bad PNG CRC rejected without storing the artwork',()=>{const b=body(),p=Buffer.from(b.png,'base64');p[30]^=1;assert.throws(()=>validateOrder({...b,png:p.toString('base64')}));});
test('unconfigured collection fails closed but a private design can be saved',async()=>{const f=fixture();try{f.env.GT3_PAYMENTS_ENABLED='false';const saved=f.c.record(body());assert.equal(saved.order.status,'draft');assert.equal((await f.c.readiness()).open,false);await assert.rejects(f.c.checkout(saved.order.id,saved.token,'x'),/not open/);assert.equal(f.calls.length,0);}finally{f.close();}});
test('approved terms and actual tax registration are independent launch gates',async()=>{const f=fixture();try{f.fake.tax.registrations.list=async()=>({data:[]});assert.equal((await f.c.readiness(true)).open,false);f.fake.tax.registrations.list=async()=>({data:[{country:'CA',status:'active'}]});f.env.GT3_CAMPAIGN_JSON='{}';assert.equal((await f.c.readiness(true)).open,false);}finally{f.close();}});
test('private saved designs persist, reject duplicate changes and require their own token',()=>{const f=fixture();try{const b=body(),a=f.c.record(b);assert.equal(f.c.record(b).order.id,a.order.id);assert.throws(()=>f.c.record({...b,company:'Different'}));assert.throws(()=>f.c.authorize(a.order.id,'bad'));const other=f.c.record({...body(),zone:'hood'});assert.throws(()=>f.c.authorize(a.order.id,other.token));f.h.close();const next=createHandler(f.options);assert.equal(next.commerce.authorize(a.order.id,a.token).artwork_sha.length,64);next.close();}finally{f.close();}});
test('server amount, correct product and opaque artwork reference enter hosted Checkout',async()=>{const f=fixture();try{const s=f.c.record({...body(),amount:1}),ready=await f.c.readiness(),r=await f.c.checkout(s.order.id,s.token,ready.termsHash),p=f.calls[0].p;assert.match(r.url,/^https:\/\/checkout.stripe.com/);assert.equal(p.line_items[0].price_data.unit_amount,s.order.amount);assert.equal(p.line_items[0].price_data.product,product);assert.equal(p.mode,'payment');assert.equal(p.automatic_tax.enabled,true);assert(!p.payment_method_types);assert(!JSON.stringify(p).includes(image));assert.match(p.integration_identifier,/_[a-z]{8}$/);assert.equal(new URL(p.success_url).search,'?payment=return');assert(new URL(p.success_url).hash.includes('key='));}finally{f.close();}});
test('current terms must be accepted before checkout',async()=>{const f=fixture();try{const s=f.c.record(body());await assert.rejects(f.c.checkout(s.order.id,s.token,'old'),/terms/);assert.equal(f.calls.length,0);}finally{f.close();}});
test('concurrent buyers cannot start paid checkouts for the same panel',async()=>{const f=fixture();try{const a=f.c.record(body()),b=f.c.record(body()),{termsHash}=await f.c.readiness();const out=await Promise.allSettled([f.c.checkout(a.order.id,a.token,termsHash),f.c.checkout(b.order.id,b.token,termsHash)]);assert.equal(out.filter(v=>v.status==='fulfilled').length,1);assert.equal(f.sessions.size,1);}finally{f.close();}});
test('same order retries reuse a Stripe session and its durable idempotency key',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();const out=await Promise.all([f.c.checkout(a.order.id,a.token,termsHash),f.c.checkout(a.order.id,a.token,termsHash)]);assert.equal(out[0].url,out[1].url);assert.equal(f.sessions.size,1);assert(f.calls.every(c=>c.options.idempotencyKey===f.calls[0].options.idempotencyKey));}finally{f.close();}});
test('uncertain creation timeout holds inventory and can be safely retried',async()=>{const f=fixture();try{const real=f.fake.checkout.sessions.create;let once=true;f.fake.checkout.sessions.create=async(...args)=>{const s=await real(...args);if(once){once=false;throw Error('connection timed out');}return s;};const a=f.c.record(body()),b=f.c.record(body()),{termsHash}=await f.c.readiness();await assert.rejects(f.c.checkout(a.order.id,a.token,termsHash));await assert.rejects(f.c.checkout(b.order.id,b.token,termsHash),/another checkout/);const r=await f.c.checkout(a.order.id,a.token,termsHash);assert(r.url);assert.equal(f.sessions.size,1);}finally{f.close();}});
test('only Stripe-confirmed expired unpaid sessions release exclusive inventory',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);const r=f.c.authorize(a.order.id,a.token);f.sessions.get(r.session_id).status='expired';const b=f.c.record(body());await f.c.checkout(b.order.id,b.token,termsHash);assert.equal(f.c.db().prepare('SELECT order_id FROM gt3_inventory').get().order_id,b.order.id);}finally{f.close();}});
test('redirect data cannot mark an order paid, while a canonical paid session can',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);let r=await f.c.reconcile(a.order.id);assert.equal(r.status,'checkout');f.paid(r.session_id);r=await f.c.reconcile(a.order.id);assert.equal(r.status,'paid');assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_inventory').get().n,1);}finally{f.close();}});
test('mismatched payment amount is never credited',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);const r=f.c.authorize(a.order.id,a.token),s=f.paid(r.session_id);s.amount_subtotal=1;await assert.rejects(f.c.reconcile(a.order.id),/reconciled/);assert.notEqual(f.c.authorize(a.order.id,a.token).status,'paid');}finally{f.close();}});
test('pending asynchronous payment retains inventory',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);const r=f.c.authorize(a.order.id,a.token);f.sessions.get(r.session_id).status='complete';assert.equal((await f.c.reconcile(a.order.id)).status,'processing');const b=f.c.record(body());await assert.rejects(f.c.checkout(b.order.id,b.token,termsHash));}finally{f.close();}});
test('refund or dispute never automatically reopens a paid placement',async()=>{const f=fixture();try{const a=f.c.record(body()),{termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);const r=f.c.authorize(a.order.id,a.token),s=f.paid(r.session_id);await f.c.reconcile(a.order.id);s.payment_intent.latest_charge.amount_refunded=100;assert.equal((await f.c.reconcile(a.order.id)).status,'review');assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_inventory').get().n,1);}finally{f.close();}});
test('HTTP saves a real design and validates raw signed webhook replays',async()=>{const f=fixture();const server=http.createServer((q,r)=>f.h.handle(q,r));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;try{
 const sessionResponse=await fetch(url+'/api/gt3/session'),cookie=sessionResponse.headers.get('set-cookie').split(';')[0],session=await sessionResponse.json();const headers={Origin:'http://localhost',Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':session.csrf};
 let res=await fetch(url+'/api/gt3/orders',{method:'POST',headers,body:JSON.stringify(body())});assert.equal(res.status,201);const a=await res.json();res=await fetch(url+'/api/gt3/order?id='+a.order.id);assert.equal(res.status,404);res=await fetch(url+'/api/gt3/order?id='+a.order.id,{headers:{Authorization:'Bearer '+a.token}});assert.equal(res.status,200);
 const {termsHash}=await f.c.readiness();await f.c.checkout(a.order.id,a.token,termsHash);const r=f.c.authorize(a.order.id,a.token),s=f.paid(r.session_id),event={id:'evt_fixture',type:'checkout.session.completed',livemode:false,data:{object:s}},raw=JSON.stringify(event),ts=Math.floor(Date.now()/1000),sign=crypto.createHmac('sha256',f.env.GT3_STRIPE_WEBHOOK_SECRET).update(ts+'.'+raw).digest('hex');
 res=await fetch(url+'/api/gt3/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':'t='+ts+',v1=bad'},body:raw});assert.equal(res.status,400);
 for(let i=0;i<2;i++){res=await fetch(url+'/api/gt3/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':'t='+ts+',v1='+sign},body:raw});assert.equal(res.status,200);}
 assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_payment_events').get().n,1);assert.equal(f.c.authorize(a.order.id,a.token).status,'paid');
 res=await fetch(url+'/api/gt3/admin/artwork?id='+a.order.id);assert.equal(res.status,401);
 }finally{await new Promise(r=>server.close(r));f.close();}});
