'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
const {createCommerce,validateOrder}=require('../commerce.cjs'),{fixture,design}=require('./direct-fixture.cjs');
function setup(open=true){const f=fixture(open),db=new DatabaseSync(':memory:');let answer;
 const c=createCommerce({database:()=>db,env:f.env,origin:'http://fixture.local',secret:f.env.SPONSOR_SESSION_SECRET,stripe:f.stripe,csrf:req=>{if(!req.authorized)throw Object.assign(Error('Forbidden'),{status:403});},admin:()=>{},rate:()=>{},json:(_,status,body)=>{answer={status,body};},readBody:async req=>req.body});
 return{...f,c,db,async send(b,authorized=true){answer=null;await c.handle({method:'POST',body:b,authorized},{},'/api/gt3/designs');return answer;},close(){db.close();}};
}
test('legacy validation is not silently loosened by client intent flags',()=>{const b=design();assert.throws(()=>validateOrder({...b,intent:'pay'}));});
test('direct pay does not need a name, company or email before Stripe',async()=>{const f=setup();try{const b=design(),r=await f.c.readiness();b.termsHash=r.termsHash;const a=await f.send(b);assert.equal(a.status,201);assert.deepEqual(a.body.order.contact,{name:'',company:'',email:''});const next=await f.c.checkout(a.body.order.id,a.body.token,r.termsHash);assert(next.url);assert(!Object.hasOwn(f.calls[0].p,'customer_email'));assert(!Object.hasOwn(f.calls[0].p,'payment_method_types'));}finally{f.close();}});
test('missing payment setup rejects anonymous records before persistence',async()=>{const f=setup(false);try{await assert.rejects(f.send(design()),/not open/);assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_orders').get().n,0);assert.equal(f.calls.length,0);}finally{f.close();}});
test('prelaunch needs one real email, no invented name/company placeholders',async()=>{const f=setup(false);try{const a=await f.send({...design(),intent:'request',email:'test@example.test'});assert.equal(a.body.order.contact.name,'');assert.equal(a.body.order.contact.company,'');assert.equal(a.body.order.contact.email,'test@example.test');assert.equal(a.body.order.status,'draft');}finally{f.close();}});
test('prelaunch rejects absent or malformed email',async()=>{const f=setup(false);try{await assert.rejects(f.send({...design(),intent:'request'}));await assert.rejects(f.send({...design(),intent:'request',email:'not-an-email'}));}finally{f.close();}});
test('artwork permission and current terms required before direct pay',async()=>{const f=setup();try{await assert.rejects(f.send({...design(),termsHash:'stale'}),/terms changed/);const r=await f.c.readiness();await assert.rejects(f.send({...design(),termsHash:r.termsHash,consent:false}),/permission/);}finally{f.close();}});
test('direct-design route retains the shared CSRF guard',async()=>{const f=setup();try{await assert.rejects(f.send(design(),false),/Forbidden/);assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_orders').get().n,0);}finally{f.close();}});
test('identical direct design retries reuse one order',async()=>{const f=setup();try{const b=design();b.termsHash=(await f.c.readiness()).termsHash;const a=await f.send(b),again=await f.send(b);assert.equal(a.body.order.id,again.body.order.id);assert.equal(a.body.token,again.body.token);assert.equal(f.c.db().prepare('SELECT COUNT(*) AS n FROM gt3_orders').get().n,1);}finally{f.close();}});
test('contact is read from the canonical paid session, not return parameters',async()=>{const f=setup();try{const b=design();b.termsHash=(await f.c.readiness()).termsHash;const a=(await f.send(b)).body;await f.c.checkout(a.order.id,a.token,b.termsHash);const row=f.c.authorize(a.order.id,a.token);assert.equal(JSON.parse(row.contact).email,'');f.paid(row.session_id);const paid=await f.c.reconcile(a.order.id);assert.equal(paid.status,'paid');assert.deepEqual(JSON.parse(paid.contact),{name:'Fixture Buyer',company:'',email:'buyer@example.test'});assert.equal(f.c.authorize(a.order.id,a.token).id,a.order.id);}finally{f.close();}});
test('anonymous buyers still cannot purchase the same space twice',async()=>{const f=setup();try{const t=(await f.c.readiness()).termsHash,a=(await f.send({...design(),termsHash:t})).body,b=(await f.send({...design(),termsHash:t})).body;const outcomes=await Promise.allSettled([f.c.checkout(a.order.id,a.token,t),f.c.checkout(b.order.id,b.token,t)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.sessions.size,1);}finally{f.close();}});
