// Real first-party geometry. Live mode is GET-only; payments in isolated tests use a fake Stripe client.
import {chromium} from '@playwright/test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const live=process.argv.includes('--live'),readonly=live||process.argv.includes('--readonly');
const out=path.resolve('sponsorship/gt3/reports');fs.mkdirSync(out,{recursive:true});
const report={scope:live?'Published direct studio, real model and GET-only checks':'Isolated real model, SQLite and mocked payment integration',checks:[],errors:[],requests:[]};
const check=(n,v)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS '+n);};
let base='https://www.brainsnn.com',server,handler,dir,browser,createHandler;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const ready=async page=>{await page.waitForFunction(()=>window.GT3_RENDER_STATUS?.ready||window.GT3_RENDER_STATUS?.fail,{},{timeout:120000});const s=await page.evaluate(()=>window.GT3_RENDER_STATUS);check('Actual Porsche geometry rendered',s.ready&&s.triangles>100000);return s;};
const image=async page=>Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.fillStyle='#a9e6ed';x.fillRect(20,83,8,74);x.fillStyle='white';x.textAlign='center';x.font='600 46px Arial';x.fillText('YOUR BRAND',276,135);return c.toDataURL('image/png').split(',')[1];}),'base64');
async function choose(page,id){await page.locator('#spot-trigger').click();await page.locator('#spot-'+id).click();await page.waitForFunction(z=>window.GT3_RENDER_STATUS.placement===z,id);}
try{
 if(!live){process.env.GT3_SKIP_PRELOAD='true';({createHandler}=createRequire(import.meta.url)('../server.cjs'));dir=fs.mkdtempSync(path.join(os.tmpdir(),'gt3-direct-'));server=http.createServer((q,r)=>handler.matches(q.url)?void handler.handle(q,r):(r.writeHead(404),r.end()));await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;handler=createHandler({origin:base,dbPath:path.join(dir,'requests.sqlite'),env:{}});}
 else {let published=false;for(let i=0;i<30;i++){try{const r=await fetch(base+'/sponsor/gt3/?verify='+Date.now(),{signal:AbortSignal.timeout(15000)});if(r.ok&&(await r.text()).includes('glass-direct-v2')){published=true;break;}}catch{}await wait(6000);}check('Expected direct glass release published',published);}
 for(const route of ['/sponsor/gt3/','/sponsor/gt3/direct.css','/sponsor/gt3/side.webp','/api/gt3/catalog']){const r=await fetch(base+route);check('HTTP 200 '+route,r.status===200);}
 browser=await chromium.launch({channel:'chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))report.requests.push({url:new URL(r.url()).origin+new URL(r.url()).pathname,method:r.method()});});
 if(readonly)await page.route('**/*',r=>['GET','HEAD'].includes(r.request().method())?r.continue():r.abort());
 await page.goto(base+'/sponsor/gt3/',{waitUntil:'domcontentloaded'});report.render=await ready(page);await page.waitForFunction(()=>!document.getElementById('primary-cta').disabled);
 check('One 3D canvas, no provider iframe',await page.locator('#scene canvas').count()===1&&await page.locator('iframe').count()===0);
 check('No duplicate checkout dialog',await page.locator('dialog').count()===0);check('No name or company form',await page.locator('input[name=name],input[name=company],#name,#company').count()===0);
 check('Email-only request while collection closed',await page.locator('body').getAttribute('data-checkout-mode')==='request'&&await page.locator('#email').isVisible());
 check('All eight glass placement options',await page.locator('#spot-options [role=option]').count()===8);
 await page.locator('#spot-trigger').focus();await page.keyboard.press('ArrowDown');check('Keyboard opens placement menu',await page.locator('#spot-trigger').getAttribute('aria-expanded')==='true');await page.keyboard.press('End');check('End selects last menu option focus',await page.locator('#spot-passenger-fender').evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');check('Escape closes menu and returns focus',await page.locator('#spot-options').isHidden()&&await page.locator('#spot-trigger').evaluate(e=>e===document.activeElement));
 await page.locator('#spot-trigger').click();check('Dropdown has genuine glass blur',await page.locator('#spot-options').evaluate(e=>getComputedStyle(e).backdropFilter.includes('blur')));await page.screenshot({path:path.join(out,live?'live-glass-menu.png':'glass-menu.png'),fullPage:true,timeout:60000});await page.keyboard.press('Escape');
 check('Glass never filters the 3D canvas',await page.locator('#scene canvas').evaluate(e=>getComputedStyle(e).filter==='none'&&getComputedStyle(e).backdropFilter==='none'));
 await page.locator('#logo').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:await image(page)});await page.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);check('Logo projects without a placement or review step',await page.evaluate(()=>window.GT3_DESIGN.snapshot().zone)==='driver-door');
 for(const id of ['hood','wing','driver-quarter','passenger-quarter','driver-fender','passenger-fender','passenger-door','driver-door']){await choose(page,id);check('Logo follows '+id,await page.evaluate(z=>window.GT3_DESIGN.snapshot().zone===z,id));}
 await page.locator('#scene canvas').scrollIntoViewIfNeeded();const box=await page.locator('#scene canvas').boundingBox(),camera=await page.evaluate(()=>window.GT3_RENDER_STATUS.camera);await page.mouse.move(box.x+box.width*.60,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.32,box.y+box.height*.5,{steps:12});await page.mouse.up();await wait(400);check('Logo remains on geometry while orbiting',JSON.stringify(camera)!==JSON.stringify(await page.evaluate(()=>window.GT3_RENDER_STATUS.camera))&&await page.evaluate(()=>window.GT3_RENDER_STATUS.decals===1));
 await page.locator('#use-cases').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.case-media img')].every(e=>e.complete&&e.naturalWidth>0));check('Four illustrated use-case cards load their images',await page.locator('.case-media img').count()===4);check('Examples are labelled concepts, not fake clients',await page.locator('.use-heading').innerText().then(s=>s.includes('Illustrative concepts')));
 await page.locator('.case-example summary').first().click();check('Concrete example expands',await page.locator('.case-example').first().evaluate(e=>e.open));await page.locator('[data-case-zone=hood]').click();await page.waitForFunction(()=>window.GT3_RENDER_STATUS.placement==='hood');check('Use-case CTA selects the right panel',await page.locator('#spot-name').innerText()==='Hood');
 await choose(page,'driver-door');await page.locator('#scene canvas').scrollIntoViewIfNeeded();await wait(500);await page.screenshot({path:path.join(out,live?'direct-live-desktop.png':'direct-desktop.png'),fullPage:true,timeout:60000});
 if(!readonly){await page.locator('#email').fill('qa@example.test');await page.locator('#art-rights').check();await page.locator('#primary-cta').click();await page.waitForFunction(()=>document.getElementById('form-status').textContent.includes('Design saved.'));
 const row=handler.commerce.db().prepare('SELECT * FROM gt3_orders').get();check('One-email request saves real isolated SQLite',row.status==='draft'&&JSON.parse(row.contact).email==='qa@example.test'&&JSON.parse(row.contact).name==='');check('Request does not create a payment',row.session_id===null);await page.locator('#primary-cta').click();await wait(300);check('Repeated request is idempotent',handler.commerce.db().prepare('SELECT COUNT(*) AS n FROM gt3_orders').get().n===1);
 await page.reload({waitUntil:'domcontentloaded'});await ready(page);await page.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);check('Saved design restores without reupload',await page.evaluate(()=>window.GT3_DESIGN.snapshot().zone)==='driver-door');}
 for(const w of [320,390,768,1024,1440]){await page.setViewportSize({width:w,height:1000});check('No horizontal overflow '+w,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:390,height:844});await choose(page,'hood');await page.locator('#scene canvas').scrollIntoViewIfNeeded();await wait(800);check('Mobile selector text is readable',await page.locator('#spot-trigger').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=16));await page.screenshot({path:path.join(out,live?'direct-live-mobile.png':'direct-mobile.png'),fullPage:true,timeout:60000});
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'},{name:'prefers-reduced-transparency',value:'reduce'}]});check('Reduced motion disables decorative animation',await page.locator('.loader-orbit').evaluate(e=>getComputedStyle(e).animationName==='none'));await page.locator('#spot-trigger').click();check('Reduced transparency disables menu blur',await page.locator('#spot-options').evaluate(e=>getComputedStyle(e).backdropFilter==='none'));await page.keyboard.press('Escape');
 check('All runtime resources same-origin',report.requests.every(r=>r.url.startsWith(base+'/')));check('No JavaScript exceptions',!report.errors.length);
 if(readonly)check('No production data submissions or payments',report.requests.every(r=>['GET','HEAD'].includes(r.method)));
 await page.close();
 if(!readonly){
  // Same actual app and SQLite, with an injected payment service. No runtime query activates sales.
  handler.close();const {fixture}=createRequire(import.meta.url)('./direct-fixture.cjs'),f=fixture(true);handler=createHandler({origin:base,dbPath:path.join(dir,'pay.sqlite'),env:f.env,stripe:f.stripe});
  const pay=await browser.newPage({viewport:{width:1440,height:1050}});pay.setDefaultTimeout(60000);await pay.goto(base+'/sponsor/gt3/',{waitUntil:'domcontentloaded'});await ready(pay);await pay.waitForFunction(()=>document.body.dataset.checkoutMode==='pay');check('Open checkout collects no duplicate email onsite',await pay.locator('#email').isHidden()&&await pay.locator('#email').isDisabled());
  await pay.locator('#logo').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:await image(pay)});await pay.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);await pay.locator('#art-rights').check();
  await pay.route('https://checkout.stripe.com/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><h1>Hosted checkout test fixture</h1>'}));
  await pay.locator('#primary-cta').click();await pay.waitForURL('https://checkout.stripe.com/**');check('One click after upload opens hosted Checkout without an extra form',f.sessions.size===1);check('Stripe, not BrainSNN, collects customer details',!Object.hasOwn(f.calls[0].p,'customer_email'));
  const order=handler.commerce.db().prepare('SELECT * FROM gt3_orders').get();check('Private artwork is attached to its checkout order',order.artwork_sha===f.calls[0].p.metadata.artwork_sha&&order.session_id!==null);
  f.paid(order.session_id);await pay.goto(f.calls[0].p.success_url,{waitUntil:'domcontentloaded'});await ready(pay);await pay.waitForFunction(()=>document.getElementById('order-status').textContent.includes('Payment confirmed by Stripe.'));check('Only canonical payment confirmation shows success',handler.commerce.db().prepare('SELECT status FROM gt3_orders').get().status==='paid');await pay.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);check('Artwork returns after hosted payment',await pay.evaluate(()=>window.GT3_DESIGN.snapshot().zone)==='driver-door');check('Confirmed order cannot start another charge',await pay.locator('#primary-cta').isDisabled());await pay.close();
 }
}catch(e){report.failure=e.stack;process.exitCode=1;}finally{
 fs.writeFileSync(path.join(out,live?'direct-live.json':'direct-native.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));handler?.close();if(dir)fs.rmSync(dir,{recursive:true,force:true});
}
