// Actual first-party WebGL and isolated HTTP/SQLite. Stripe calls are tested separately.
import {chromium} from '@playwright/test';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
process.env.GT3_SKIP_PRELOAD='true';const require=createRequire(import.meta.url),{createHandler}=require('../server.cjs');
const out=path.resolve('sponsorship/gt3/reports');fs.mkdirSync(out,{recursive:true});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gt3-ux-'));let handler;
const server=http.createServer((q,r)=>handler.matches(q.url)?void handler.handle(q,r):(r.writeHead(404),r.end()));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;handler=createHandler({origin:base,dbPath:path.join(dir,'qa.sqlite'),env:{}});
const browser=await chromium.launch({channel:'chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={scope:'Real Porsche geometry, automatic logo projection and isolated saved designs; no live Stripe charges',checks:[],errors:[],requests:[]};
const check=(name,v)=>{assert(v,name);report.checks.push(name);};
async function ready(page){await page.waitForFunction(()=>window.GT3_RENDER_STATUS?.ready||window.GT3_RENDER_STATUS?.fail,{},{timeout:120000});const r=await page.evaluate(()=>window.GT3_RENDER_STATUS);check('Actual model renders triangles',r.ready&&r.triangles>100000);return r;}
async function logo(page){return page.evaluate(()=>{const c=document.createElement('canvas');c.width=512;c.height=200;const x=c.getContext('2d');x.fillStyle='#7de5f1';x.fillRect(10,30,70,70);x.fillStyle='#fff';x.font='bold 60px Arial';x.fillText('YOUR BRAND',95,93);return c.toDataURL('image/png').split(',')[1];});}
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(/^http/.test(r.url()))report.requests.push(new URL(r.url()).origin+new URL(r.url()).pathname);});
 await page.goto(base+'/sponsor/gt3/',{waitUntil:'domcontentloaded'});report.render=await ready(page);check('One first-party canvas, no iframe',await page.locator('#scene canvas').count()===1&&await page.locator('iframe').count()===0);check('Eight placements remain',await page.locator('#placement option').count()===8);check('One concise three-step flow',await page.locator('.steps span').count()===3);check('No extra place button',await page.locator('#place-logo').count()===0);
 await page.locator('#logo').setInputFiles({name:'test-logo.png',mimeType:'image/png',buffer:Buffer.from(await logo(page),'base64')});await page.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);check('Upload immediately projects a logo on the real car',await page.evaluate(()=>window.GT3_DESIGN.snapshot().zone)==='driver-door');
 for(const zone of ['driver-door','passenger-door','hood','wing','driver-quarter','passenger-quarter','driver-fender','passenger-fender']){await page.locator('#placement').selectOption(zone);await page.waitForFunction(z=>window.GT3_RENDER_STATUS.decals===1&&window.GT3_RENDER_STATUS.placement===z,zone);check('Automatic surface placement: '+zone,await page.evaluate(z=>window.GT3_DESIGN.snapshot().zone===z,zone));await page.locator('#scene canvas').scrollIntoViewIfNeeded();await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'auto-'+zone+'.png'),fullPage:true,timeout:60000});}
 await page.locator('#placement').selectOption('driver-door');const before=await page.evaluate(()=>window.GT3_RENDER_STATUS.camera);const c=page.locator('#scene canvas');await c.scrollIntoViewIfNeeded();const box=await c.boundingBox();await page.mouse.move(box.x+box.width*.58,box.y+box.height*.52);await page.mouse.down();await page.mouse.move(box.x+box.width*.35,box.y+box.height*.52,{steps:18});await page.mouse.up();await page.waitForTimeout(300);check('Pointer orbit changes the actual camera',JSON.stringify(before)!==JSON.stringify(await page.evaluate(()=>window.GT3_RENDER_STATUS.camera)));
 await page.locator('#reset-view').click();await page.locator('#primary-cta').click();await page.waitForFunction(()=>!document.getElementById('submit').disabled);check('Review includes the actual logo',await page.locator('#review-logo').evaluate(e=>e.complete&&e.naturalWidth===512));check('Unconfigured checkout is honestly a request',await page.locator('#submit').textContent().then(t=>t.includes('request checkout')));
 await page.locator('#name').fill('Test Sponsor');await page.locator('#company').fill('QA only');await page.locator('#email').fill('qa@example.test');await page.locator('#art-rights').check();await page.locator('#submit').click();await page.waitForFunction(()=>document.getElementById('form-status').textContent.includes('Design saved.'));
 const order=handler.commerce.db().prepare('SELECT * FROM gt3_orders').get();check('Real local SQLite stores a private normalized design',order.status==='draft'&&order.artwork.length>100&&order.artwork_sha.length===64);check('No Stripe session created',order.session_id===null);await page.locator('#submit').click();await page.waitForTimeout(200);check('Repeated submission does not duplicate designs',handler.commerce.db().prepare('SELECT COUNT(*) AS n FROM gt3_orders').get().n===1);
 await page.keyboard.press('Escape');await page.reload({waitUntil:'domcontentloaded'});await ready(page);await page.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);check('Saved artwork restores after page reload',await page.evaluate(()=>window.GT3_DESIGN.snapshot().zone)==='driver-door');
 await page.screenshot({path:path.join(out,'checkout-desktop.png'),fullPage:true,timeout:60000});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});check('No horizontal overflow at '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});await mobile.goto(base+'/sponsor/gt3/',{waitUntil:'domcontentloaded'});await ready(mobile);await mobile.locator('#logo').setInputFiles({name:'test-logo.png',mimeType:'image/png',buffer:Buffer.from(await logo(mobile),'base64')});await mobile.waitForFunction(()=>window.GT3_RENDER_STATUS.decals===1);await mobile.locator('#scene canvas').scrollIntoViewIfNeeded();await mobile.waitForTimeout(1000);await mobile.screenshot({path:path.join(out,'checkout-mobile.png'),fullPage:true,timeout:60000});check('Mobile-width view auto-projects the logo',await mobile.evaluate(()=>window.GT3_RENDER_STATUS.decals===1));await mobile.close();
 await page.locator('.art-details summary').click();await page.locator('#remove-logo').click();check('Cleared artwork cannot be submitted',await page.evaluate(()=>{try{window.GT3_DESIGN.snapshot();return false;}catch{return true;}}));
 check('No third-party model or artwork requests',report.requests.every(u=>u.startsWith(base)));check('No top-level JavaScript errors',report.errors.length===0);
}catch(e){report.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'checkout-native.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));handler.close();fs.rmSync(dir,{recursive:true,force:true});}
