// Real geometry, real WebGL, real pointer input. Proposals use isolated temporary storage.
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';
process.env.GT3_SKIP_PRELOAD='true';const require=createRequire(import.meta.url),{createHandler}=require('../server.cjs');const out=path.resolve('sponsorship/gt3/reports'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'native-gt3-'));fs.mkdirSync(out,{recursive:true});
let handler;const server=http.createServer((q,r)=>handler.matches(q.url)?handler.handle(q,r):(r.writeHead(404),r.end()));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;handler=createHandler({origin:base,dbPath:path.join(temp,'data.sqlite'),env:{}});
const report={renderer:'Real Three.js WebGL with exact CC-BY Porsche geometry, no mocks',checks:[],errors:[],requests:[]};const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS '+name);};const browser=await chromium.launch({channel:'chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))report.requests.push(r.url());});await page.goto(base+'/sponsor/gt3/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.GT3_RENDER_STATUS?.ready||window.GT3_RENDER_STATUS?.fail,{},{timeout:120000});report.render=await page.evaluate(()=>window.GT3_RENDER_STATUS);await page.waitForTimeout(600);check('Actual model rendered triangles',report.render.ready&&report.render.triangles>100000);check('No embedded provider iframe',await page.locator('iframe').count()===0);check('Eight placements',await page.locator('#placement option').count()===8);await page.screenshot({path:path.join(out,'native-desktop.png'),fullPage:true,timeout:60000});
 const c=page.locator('#scene canvas');await c.scrollIntoViewIfNeeded();const box=await c.boundingBox(),before=await page.screenshot({path:path.join(out,'native-before.png'),timeout:60000});const initial=await page.evaluate(()=>window.GT3_RENDER_STATUS.camera);await page.mouse.move(box.x+box.width*.6,box.y+box.height*.52);await page.mouse.down();await page.mouse.move(box.x+box.width*.25,box.y+box.height*.54,{steps:6});await page.mouse.up();await page.mouse.move(5,5);await page.waitForTimeout(1500);report.afterDrag=await page.evaluate(()=>window.GT3_RENDER_STATUS);check('Pointer drag changes actual 3D camera',JSON.stringify(initial)!==JSON.stringify(report.afterDrag.camera));check('Changed camera is rendered',report.afterDrag.frames>report.render.frames);const after=await page.screenshot({path:path.join(out,'native-after.png'),timeout:60000});check('Rendered car pixels change after drag',!before.equals(after));await page.locator('#reset-view').click();await page.waitForTimeout(700);check('Reset keeps single canvas',await page.locator('#scene canvas').count()===1);
 await page.locator('.art-details summary').click();await page.locator('#brand-name').fill('BRAIN SNN');await page.locator('#place-logo').click();check('Local artwork requires permission',(await page.locator('#art-status').textContent()).includes('Confirm'));await page.locator('#art-rights').check();await page.locator('#place-logo').click();await c.scrollIntoViewIfNeeded();const artBox=await c.boundingBox();for(const [x,y] of [[.5,.55],[.45,.58],[.4,.55],[.55,.6]]){await page.mouse.click(artBox.x+artBox.width*x,artBox.y+artBox.height*y);await page.waitForTimeout(100);if(await page.evaluate(()=>window.GT3_RENDER_STATUS.decals===1))break;}check('Actual geometry accepts an on-surface text decal',await page.evaluate(()=>window.GT3_RENDER_STATUS.decals===1));await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'native-logo.png'),fullPage:true,timeout:60000});await page.locator('#brand-name').fill('CHANGED');await page.waitForTimeout(200);check('Text edit preserves one decal',await page.evaluate(()=>window.GT3_RENDER_STATUS.decals===1));await page.locator('#remove-logo').click();check('Remove disposes the selected decal',await page.evaluate(()=>window.GT3_RENDER_STATUS.decals===0));await page.locator('.art-details summary').click();
 await page.locator('#placement').selectOption('hood');check('Selection updates proposal',await page.locator('#form-zone').textContent()==='Hood');await page.locator('.proposal').click();await page.waitForFunction(()=>!document.getElementById('submit').disabled);await page.locator('#name').fill('QA Person');await page.locator('#company').fill('Temporary QA');await page.locator('#email').fill('qa@example.test');await page.locator('#proposed-budget').fill('10000');await page.locator('#brief').fill('Temporary test of local proposal persistence. Not a real application.');await page.locator('input[name=consent]').check();await page.locator('#submit').click();await page.waitForFunction(()=>document.getElementById('form-status').textContent.includes('Proposal saved. Reference'));check('Private proposal stored in actual isolated database',handler.database().prepare('SELECT COUNT(*) n FROM gt3_proposals').get().n===1);check('Duplicate form submit disabled',await page.locator('#submit').isDisabled());await page.keyboard.press('Escape');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.waitForTimeout(200);check('No overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.GT3_RENDER_STATUS?.ready,{},{timeout:120000});await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'native-mobile.png'),fullPage:true,timeout:60000});check('Model renders on narrow layout',await page.evaluate(()=>window.GT3_RENDER_STATUS.triangles>100000));check('All runtime network requests same origin',report.requests.every(u=>u.startsWith(base)));check('No top-level JavaScript errors',report.errors.length===0);
 const bad=await browser.newPage();await bad.route('**/car.glb*',r=>r.abort());await bad.goto(base+'/sponsor/gt3/');await bad.waitForFunction(()=>document.body.dataset.renderState==='error');check('Failed model is not reported ready',!(await bad.evaluate(()=>window.GT3_RENDER_STATUS.ready)));check('Failure offers retry',await bad.locator('#retry').isVisible());
}catch(e){report.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'native-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));handler.close();fs.rmSync(temp,{recursive:true,force:true});}
