import { audioPointAtTime, unavailableAudioTimeline } from './audioFeatures.js';
import { buildMultimodalFusion } from './mediaFusion.js';
import { formatTranscriptTime, parseTimedTranscript } from './timedTranscript.js';

function compact(value = '', max = 180) {
  const text = String(value || '').replace(/\s+/g, ' ').trim();
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

function formatRange(start, end) {
  return `${formatTranscriptTime(start)}–${formatTranscriptTime(end)}`;
}

function decorateTranscriptTimeline(timeline, media) {
  const localTranscript = media?.localTranscript;
  const localAsr = localTranscript?.status === 'ready';
  if (localAsr) {
    return {
      ...timeline,
      timingOrigin: 'local-asr',
      timingIsMeasured: false,
      disclaimer: 'Transcript text and word timing were generated by a browser-local speech model. They can contain recognition or timing errors and are not user-supplied captions or measured ground truth; verify critical moments against playback.',
      localTranscript: {
        schemaVersion: localTranscript.schemaVersion,
        provider: localTranscript.provider,
        model: localTranscript.model,
        device: localTranscript.device,
        timing: localTranscript.timing,
        wordCount: localTranscript.wordCount || 0,
        segmentCount: localTranscript.segmentCount || 0,
        rawAudioUploaded: localTranscript.rawAudioUploaded === true,
      },
    };
  }
  return {
    ...timeline,
    timingOrigin: timeline?.mode === 'timed' ? 'supplied' : timeline?.mode === 'estimated' ? 'estimated' : 'none',
    timingIsMeasured: false,
  };
}

function transcriptTimingPrefix(timeline) {
  if (timeline?.timingOrigin === 'local-asr') return 'Near';
  if (timeline?.timingOrigin === 'supplied') return 'At';
  if (timeline?.mode === 'estimated') return 'Around';
  return 'In';
}

function transcriptConfidence(timeline) {
  if (timeline?.timingOrigin === 'local-asr') return 'local ASR model timing';
  if (timeline?.timingOrigin === 'supplied') return 'provided timestamp';
  return 'estimated timing';
}

function transcriptAlignmentLabel(timeline) {
  if (timeline?.timingOrigin === 'local-asr') return 'local-asr';
  return timeline?.mode || 'none';
}

function momentForSegment(segment, audioTimeline, transcriptTimeline) {
  const audio = audioPointAtTime(audioTimeline, segment.start);
  const labelMap = {
    claim: 'Claim appears',
    proof: 'Proof / measurable support',
    cta: 'Call to action',
    price: 'Price / commercial ask',
    workflow: 'Workflow action',
  };
  const actionMap = {
    claim: 'Keep supporting proof close to this claim; soften it if evidence is not yet visible.',
    proof: 'Keep this evidence visually adjacent to the claim it supports.',
    cta: 'Confirm the viewer has seen enough proof before this ask.',
    price: 'Avoid making price carry the credibility burden; establish value/proof first.',
    workflow: 'Check whether this step is necessary or can be shortened for client-facing content.',
  };
  return {
    id: `client-${segment.id}`,
    start: segment.start,
    end: segment.end,
    kind: segment.kind,
    label: labelMap[segment.kind] || 'Narration',
    detail: compact(segment.text, 220),
    whyItMatters: segment.kind === 'proof'
      ? 'This is evidence the viewer can use to evaluate the surrounding claim.'
      : segment.kind === 'cta'
        ? 'This is the moment the creative asks the viewer to act.'
        : segment.kind === 'price'
          ? 'Commercial friction enters here; proof and value should already be established.'
          : segment.kind === 'claim'
            ? 'A claim creates a credibility obligation: the next beats should support it.'
            : 'This is a semantic beat from the transcript layer.',
    action: actionMap[segment.kind] || 'Review whether this beat earns its time in the final cut.',
    confidence: transcriptConfidence(transcriptTimeline),
    source: transcriptTimeline?.timingOrigin === 'local-asr' ? 'local speech-to-text' : 'transcript',
    audioEnergy: audio?.energy ?? null,
  };
}

function buildClientMoments(baseResult, transcriptTimeline, audioTimeline) {
  const moments = [];
  const windows = baseResult?.temporalReadout?.windows || {};

  if (windows.largestDrop?.attentionDrop > 0) {
    moments.push({
      id: 'visual-largest-drop',
      start: windows.largestDrop.start,
      end: windows.largestDrop.end,
      kind: 'drop',
      label: 'Largest visual-attention-proxy drop',
      detail: `${windows.largestDrop.attentionDrop}-point decline across this five-second review window.`,
      whyItMatters: 'This is the strongest pacing/change warning in the browser-local visual heuristic.',
      action: 'Review the full span for dead time, dense explanation, weak visual support, or an unnecessary transition.',
      confidence: 'visual proxy',
      source: 'visual',
      audioEnergy: audioPointAtTime(audioTimeline, windows.largestDrop.start)?.energy ?? null,
    });
  }

  if (windows.weakest) {
    moments.push({
      id: 'visual-weakest',
      start: windows.weakest.start,
      end: windows.weakest.end,
      kind: 'weakest',
      label: 'Weakest visual-attention-proxy window',
      detail: `${windows.weakest.attentionProxy}/100 average proxy across five seconds.`,
      whyItMatters: 'The visual-change heuristic is lowest here, making this a useful review target.',
      action: 'Check whether the scene needs a tighter cut, stronger demonstration, or less explanation.',
      confidence: 'visual proxy',
      source: 'visual',
      audioEnergy: audioPointAtTime(audioTimeline, windows.weakest.start)?.energy ?? null,
    });
  }

  if (windows.strongest) {
    moments.push({
      id: 'visual-strongest',
      start: windows.strongest.start,
      end: windows.strongest.end,
      kind: 'strongest',
      label: 'Strongest response-change window',
      detail: `${windows.strongest.responseChange}/100 average visual response-change signal.`,
      whyItMatters: 'This is where the creative changes most strongly in the current visual model.',
      action: 'If the message here matters, keep its meaning clear and avoid stacking unrelated claims into the same burst.',
      confidence: 'visual proxy',
      source: 'visual',
      audioEnergy: audioPointAtTime(audioTimeline, windows.strongest.start)?.energy ?? null,
    });
  }

  for (const segment of (transcriptTimeline?.segments || []).filter((item) => item.kind !== 'narration').slice(0, 18)) {
    moments.push(momentForSegment(segment, audioTimeline, transcriptTimeline));
  }

  return moments
    .sort((a, b) => a.start - b.start || a.end - b.end)
    .slice(0, 24);
}

function anchor(kind, segment, transcriptTimeline) {
  if (!segment) return null;
  return {
    kind,
    start: segment.start,
    end: segment.end,
    label: `${kind.toUpperCase()} · ${formatRange(segment.start, segment.end)}`,
    text: compact(segment.text, 130),
    alignment: transcriptAlignmentLabel(transcriptTimeline),
  };
}

function buildClientBrief(baseResult, transcriptTimeline, audioTimeline) {
  const sequence = transcriptTimeline?.sequence || {};
  const windows = baseResult?.temporalReadout?.windows || {};
  const localAsr = transcriptTimeline?.timingOrigin === 'local-asr';
  const suppliedTiming = transcriptTimeline?.timingOrigin === 'supplied';
  const timingWord = localAsr
    ? 'model-generated local speech timing'
    : suppliedTiming
      ? 'exact supplied timing'
      : transcriptTimeline?.mode === 'estimated'
        ? 'estimated timing'
        : 'visual timing only';
  let headline = 'Client-ready creative review';
  let primaryIssue = 'No major semantic sequencing issue could be timed from the available transcript.';
  let businessRisk = 'The client may spend against a creative before proof, pacing and CTA order are clearly reviewed.';
  let exactEdit = baseResult?.recommendedEdit?.instruction || 'Review the weakest five-second window and keep measurable proof close to the claim it supports.';

  if (sequence.firstClaim && sequence.firstProof && sequence.claimProofGapSeconds != null && sequence.claimProofGapSeconds > 1) {
    const prefix = transcriptTimingPrefix(transcriptTimeline);
    headline = 'Proof arrives after the claim';
    primaryIssue = `${prefix} ${formatTranscriptTime(sequence.firstClaim.start)}, the creative introduces “${compact(sequence.firstClaim.text, 100)}”. The first detected proof appears at ${formatTranscriptTime(sequence.firstProof.start)}, ${sequence.claimProofGapSeconds.toFixed(1)}s later.`;
    businessRisk = 'The viewer is asked to accept the claim before seeing support, which can weaken trust and make the eventual CTA work harder.';
    exactEdit = localAsr
      ? `Local speech-to-text places the proof near ${formatTranscriptTime(sequence.firstProof.start)} and the claim near ${formatTranscriptTime(sequence.firstClaim.start)}. Move the proof immediately after—or before—the claim, then verify the final cut points against playback because these word timestamps are model-generated.`
      : suppliedTiming
        ? `Move the proof at ${formatTranscriptTime(sequence.firstProof.start)} to immediately follow—or precede—the claim at ${formatTranscriptTime(sequence.firstClaim.start)}. Keep the claim-to-proof gap under roughly two seconds in the next cut.`
        : `The transcript suggests the proof follows the claim by about ${sequence.claimProofGapSeconds.toFixed(1)}s. Move that proof earlier, but verify the exact edit point in the source video because this transcript alignment is estimated.`;
  } else if (sequence.firstClaim && !sequence.firstProof) {
    headline = 'Claim detected without measurable support';
    primaryIssue = `${transcriptTimingPrefix(transcriptTimeline)} ${formatTranscriptTime(sequence.firstClaim.start)}, the transcript makes a claim but no proof/customer/result segment was detected afterward.`;
    businessRisk = 'An unsupported commercial claim can lower credibility and make pricing or CTA moments feel premature.';
    exactEdit = `Add one concrete result, customer example, benchmark, demonstration or measurable constraint immediately after “${compact(sequence.firstClaim.text, 115)}”.${localAsr ? ' Verify the spoken wording and edit point against playback.' : ''}`;
  } else if (sequence.firstPrice && sequence.firstProof && sequence.firstPrice.start < sequence.firstProof.start) {
    headline = 'Price appears before proof';
    primaryIssue = `${transcriptTimingPrefix(transcriptTimeline)} ${formatTranscriptTime(sequence.firstPrice.start)}, price/commercial language appears before the first detected proof at ${formatTranscriptTime(sequence.firstProof.start)}.`;
    businessRisk = 'The viewer encounters friction before the creative has established enough evidence or value.';
    exactEdit = `Move the proof/demo ahead of the price reveal, or delay the price until the value proposition is already supported.${localAsr ? ' Verify the local-ASR timestamps against playback before making the final cut.' : ''}`;
  } else if (windows.largestDrop?.attentionDrop > 0) {
    headline = 'One five-second span deserves a tighter cut';
    primaryIssue = `${formatRange(windows.largestDrop.start, windows.largestDrop.end)} contains the largest within-window visual-attention-proxy decline (${windows.largestDrop.attentionDrop} points).`;
    businessRisk = 'If this span also contains explanation or a key claim, the creative may be spending valuable runtime in its weakest pacing window.';
    exactEdit = `Review ${formatRange(windows.largestDrop.start, windows.largestDrop.end)} first. Remove dead time, shorten explanation, or move a demonstration/proof beat into this span if the message needs support.`;
  }

  const evidenceAnchors = [
    anchor('claim', sequence.firstClaim, transcriptTimeline),
    anchor('proof', sequence.firstProof, transcriptTimeline),
    anchor('price', sequence.firstPrice, transcriptTimeline),
    anchor('cta', sequence.firstCta, transcriptTimeline),
  ].filter(Boolean);

  if (windows.largestDrop) {
    evidenceAnchors.push({
      kind: 'drop',
      start: windows.largestDrop.start,
      end: windows.largestDrop.end,
      label: `DROP · ${formatRange(windows.largestDrop.start, windows.largestDrop.end)}`,
      text: `${windows.largestDrop.attentionDrop || 0}-point within-window attention-proxy decline`,
      alignment: 'visual proxy',
    });
  }

  return {
    status: 'client-ready',
    alignmentMode: transcriptAlignmentLabel(transcriptTimeline),
    timingLabel: timingWord,
    headline,
    primaryIssue,
    businessRisk,
    exactEdit,
    evidenceAnchors: evidenceAnchors.slice(0, 8),
    presenterNotes: [
      localAsr
        ? `Speech was transcribed locally in the browser with ${transcriptTimeline.localTranscript?.model || 'Whisper'}. Word timestamps are model-generated review cues, not measured or user-supplied ground truth; verify critical moments against playback.`
        : suppliedTiming
          ? 'Transcript timestamps were supplied by the user, so semantic events can be shown at those caption times.'
          : transcriptTimeline?.mode === 'estimated'
            ? 'Transcript timing is estimated from the video duration; present these ranges as review cues, not exact spoken-word timestamps.'
            : 'No timed transcript is available; only visual timing can be presented as time-localized.',
      audioTimeline?.status === 'ready'
        ? 'Audio energy/dynamics were decoded locally in the browser. The separate local speech layer can generate text, but neither layer identifies speakers or infers emotion.'
        : 'No usable audio envelope was available, so the client brief does not make audio-energy claims.',
      'The visual timeline is a modelled browser-local creative proxy. It is not measured human attention, EEG, fMRI, biometric data or purchase intent.',
    ],
  };
}

function buildPacketExtension(transcriptTimeline, audioTimeline, clientBrief, clientMoments) {
  const transcriptOrigin = transcriptTimeline?.timingOrigin || transcriptTimeline?.mode || 'none';
  const lines = [
    '',
    '[BrainSNN client-ready multimodal v0.3]',
    `Transcript alignment: ${transcriptOrigin} (${transcriptTimeline.sourceFormat}; confidence ${transcriptTimeline.confidence})`,
    `Client brief: ${clientBrief.headline}`,
    `Primary issue: ${clientBrief.primaryIssue}`,
    `Recommended edit: ${clientBrief.exactEdit}`,
  ];

  if (transcriptTimeline?.timingOrigin === 'local-asr') {
    lines.push(`Speech provenance: browser-local ${transcriptTimeline.localTranscript?.model || 'Whisper'} via ${transcriptTimeline.localTranscript?.provider || 'Transformers.js'}; timestamps are model-generated and require verification for critical edits.`);
  }

  if (transcriptTimeline.segments.length) {
    lines.push('Timed/estimated transcript beats:');
    for (const segment of transcriptTimeline.segments.slice(0, 12)) {
      lines.push(`- ${formatRange(segment.start, segment.end)} [${segment.kind}] ${compact(segment.text, 160)}`);
    }
  }

  if (audioTimeline.status === 'ready') {
    lines.push(`Audio envelope: mean energy ${audioTimeline.summary.meanEnergy}/100; max ${audioTimeline.summary.maxEnergy}/100; silent fraction ${Math.round(audioTimeline.summary.silentFraction * 100)}%.`);
  } else {
    lines.push(`Audio envelope: unavailable (${compact(audioTimeline.reason || 'not decoded', 120)}).`);
  }

  if (clientMoments.length) {
    lines.push('Client moments:');
    for (const moment of clientMoments.slice(0, 10)) lines.push(`- ${formatRange(moment.start, moment.end)} ${moment.label}: ${compact(moment.detail, 140)}`);
  }
  return lines.join('\n');
}

export function buildClientMultimodalFusion({ text = '', media = null } = {}) {
  const base = buildMultimodalFusion({ text, media });
  const parsedTranscript = parseTimedTranscript(text, Number(media?.duration) || 0);
  const transcriptTimeline = decorateTranscriptTimeline(parsedTranscript, media);
  const audioTimeline = media?.audio?.schemaVersion
    ? media.audio
    : unavailableAudioTimeline(media?.audio?.reason || 'No browser-local audio envelope was attached to this scan.');
  const timelineTracks = [
    ...(base.result.temporalReadout?.tracks || []),
    ...(audioTimeline.status === 'ready' ? audioTimeline.tracks : []),
  ];
  const clientMoments = buildClientMoments(base.result, transcriptTimeline, audioTimeline);
  const clientBrief = buildClientBrief(base.result, transcriptTimeline, audioTimeline);
  const recommendedEdit = {
    headline: clientBrief.headline,
    instruction: clientBrief.exactEdit,
    timingNote: transcriptTimeline.timingOrigin === 'local-asr'
      ? 'Timing comes from browser-local Whisper word timestamps. Treat these as model-generated review cues and verify exact cut points against playback.'
      : transcriptTimeline.timingOrigin === 'supplied'
        ? 'Edit timing uses user-supplied transcript/caption timestamps.'
        : transcriptTimeline.mode === 'estimated'
          ? 'Timing is estimated from transcript sentence length across the video duration; verify exact edit points in the source file.'
          : base.result.recommendedEdit?.timingNote,
  };

  const transcriptProvenance = transcriptTimeline.timingOrigin === 'local-asr'
    ? `browser-local speech-to-text via ${transcriptTimeline.localTranscript?.model || 'Whisper'} / ${transcriptTimeline.localTranscript?.provider || 'Transformers.js'}; model-generated word timing; raw audio not uploaded by this layer`
    : transcriptTimeline.timingOrigin === 'supplied'
      ? `user-supplied timed transcript (${transcriptTimeline.sourceFormat})`
      : transcriptTimeline.mode === 'estimated'
        ? 'operator-supplied transcript; timing estimated locally from sentence length and video duration'
        : 'none';

  const result = {
    ...base.result,
    schemaVersion: 'brainsnn.multimodal.v0.3',
    temporalReadout: {
      ...(base.result.temporalReadout || {}),
      schemaVersion: 'brainsnn.temporal.v0.3',
      tracks: timelineTracks,
      modalities: {
        visual: Boolean(base.result.temporalReadout?.tracks?.length),
        audio: audioTimeline.status === 'ready',
        transcript: transcriptTimeline.mode !== 'none',
        transcriptAlignment: transcriptAlignmentLabel(transcriptTimeline),
      },
    },
    transcriptTimeline,
    audioTimeline,
    timelineTracks,
    clientMoments,
    clientBrief,
    recommendedEdit,
    provenance: {
      ...base.result.provenance,
      transcript: transcriptProvenance,
      audio: audioTimeline.status === 'ready'
        ? 'browser-local decoded PCM energy/dynamics envelope; no speaker identity or emotion inference'
        : `unavailable: ${audioTimeline.reason || 'not decoded'}`,
    },
    disclaimer: transcriptTimeline.timingOrigin === 'local-asr'
      ? 'V0.3 combines browser-local visual-change proxies, local audio energy/dynamics, and browser-local speech-to-text. Speech and word timestamps are model-generated and can be wrong; they are not measured human timing or user-supplied ground truth. BrainSNN does not measure human attention, emotion, cognition, purchase intent, EEG, fMRI or neural activity, and does not identify speakers or people.'
      : 'V0.3 combines browser-local visual-change proxies, optional local audio energy/dynamics, and user-supplied transcript timing or clearly labelled estimated alignment. It does not measure human attention, emotion, cognition, purchase intent, EEG, fMRI or neural activity, and does not identify speakers or people.',
  };

  return {
    packet: `${base.packet}${buildPacketExtension(transcriptTimeline, audioTimeline, clientBrief, clientMoments)}`,
    result,
  };
}
