import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { DecalGeometry } from 'three/addons/geometries/DecalGeometry.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
const host=document.getElementById('scene'),status=document.getElementById('load-status');
const state={ready:false,frames:0,triangles:0,drawCalls:0,modelMeshes:0,camera:[],decals:0,fail:null};
Object.defineProperty(window,'GT3_RENDER_STATUS',{get:()=>({...state,camera:camera?.position.toArray()||[]})});
let renderer,camera,controls,scene,model,raf=0,visible=true,disposed=false;
const vector=new THREE.Vector3(),target=new THREE.Vector3(0,.65,0),home=new THREE.Vector3();
function fail(message){state.ready=false;state.fail=message;document.body.dataset.renderState='error';status.textContent=message;host.setAttribute('aria-busy','false');document.getElementById('place-logo').disabled=true;document.getElementById('retry').hidden=false;}
function schedule(){if(!raf&&visible&&!document.hidden&&!disposed)raf=requestAnimationFrame(frame);}
function frame(){raf=0;if(!renderer||!model||!visible||document.hidden||disposed)return;const moving=controls.update();renderer.render(scene,camera);state.frames++;state.triangles=renderer.info.render.triangles;state.drawCalls=renderer.info.render.calls;if(!state.ready&&state.triangles>1000){state.ready=true;document.getElementById('place-logo').disabled=false;document.body.dataset.renderState='ready';status.textContent='Drag to rotate · Pinch or scroll to zoom';host.setAttribute('aria-busy','false');}if(moving)schedule();}
function resize(){if(!renderer||!camera)return;const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();schedule();}
function fit(){const distance=Math.max(6.2,2.7/(Math.max(.65,camera.aspect)*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))));home.set(1,.30,1.65).normalize().multiplyScalar(distance).add(target);camera.position.copy(home);controls.target.copy(target);controls.update();schedule();}
function mergeCar(root){
 root.updateMatrixWorld(true);const groups=new Map(),result=new THREE.Group();
 root.traverse(o=>{
  if(!o.isMesh)return;if(o.isSkinnedMesh||o.morphTargetInfluences||Array.isArray(o.material))throw Error('Unexpected animated mesh');
  let g=o.geometry.clone();if(g.index){const tmp=g.toNonIndexed();g.dispose();g=tmp;}
  // Reflection reverses triangle winding. Correct all attributes before baking.
  if(o.matrixWorld.determinant()<0){for(const attr of Object.values(g.attributes)){for(let i=0;i<attr.count;i+=3){for(let k=0;k<attr.itemSize;k++){const a=(i+1)*attr.itemSize+k,b=(i+2)*attr.itemSize+k,tmp=attr.array[a];attr.array[a]=attr.array[b];attr.array[b]=tmp;}}}}
  g.applyMatrix4(o.matrixWorld);
  for(const name of Object.keys(g.attributes))if(!['position','normal','uv'].includes(name))g.deleteAttribute(name);
  if(!g.attributes.normal)g.computeVertexNormals();if(!g.attributes.uv)g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(g.attributes.position.count*2),2));
  o.material.vertexColors=false;const key=o.material.uuid;if(!groups.has(key))groups.set(key,{material:o.material,list:[]});groups.get(key).list.push(g);
 });
 for(const {material,list}of groups.values()){const geometry=mergeGeometries(list,false);if(!geometry)throw Error('Model geometry could not be combined.');geometry.computeBoundingSphere();const mesh=new THREE.Mesh(geometry,material);mesh.name=material.name;result.add(mesh);list.forEach(g=>g.dispose());}return result;
}
async function init(){try{
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'default'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
 renderer.domElement.setAttribute('aria-label','Interactive Porsche GT3 RS. Drag to orbit; use reset or arrow keys.');renderer.domElement.tabIndex=0;host.prepend(renderer.domElement);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();if(raf)cancelAnimationFrame(raf);raf=0;fail('The 3D connection paused. Reload the model to continue.');});
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(32,1,.05,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.enablePan=false;controls.minDistance=3.8;controls.maxDistance=15;controls.minPolarAngle=.18;controls.maxPolarAngle=Math.PI/2-.015;controls.rotateSpeed=.6;controls.zoomSpeed=.7;controls.addEventListener('change',schedule);
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;room.dispose();pmrem.dispose();scene.environmentIntensity=.8;
 scene.add(new THREE.HemisphereLight(0xc5e7ff,0x27304c,.65));for(const [color,intensity,pos]of [[0xd5f3ff,1.4,[2,5,4]],[0x9065ff,1.1,[-3,3,-4]],[0x48d6ff,.8,[1,2,4]]]){const l=new THREE.DirectionalLight(color,intensity);l.position.set(...pos);scene.add(l);}
 resize();status.textContent='Loading Porsche geometry…';const response=await fetch('/sponsor/gt3/car.glb?v=native1',{cache:'force-cache',signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('Model download failed.');const buffer=await response.arrayBuffer();const gltf=await new GLTFLoader().parseAsync(buffer,'');model=mergeCar(gltf.scene);
 let box=new THREE.Box3().setFromObject(model),size=box.getSize(vector).clone();if(size.z>size.x)model.rotation.y=Math.PI/2;box.setFromObject(model);size=box.getSize(vector).clone();model.scale.setScalar(4.6/Math.max(size.x,size.z));box.setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);
 for(const m of model.children)if(m.material.name==='TwiXeR_992_carPaint.003'){m.material.color.setRGB(.095,.12,.15);m.material.metalness=.45;m.material.roughness=.32;}
 state.modelMeshes=model.children.length;scene.add(model);
 const disk=document.createElement('canvas');disk.width=disk.height=128;const cx=disk.getContext('2d'),gradient=cx.createRadialGradient(64,64,8,64,64,64);gradient.addColorStop(0,'rgba(0,0,0,.6)');gradient.addColorStop(1,'rgba(0,0,0,0)');cx.fillStyle=gradient;cx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(6,3.4),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(disk),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.02;scene.add(shadow);
 installPicking();fit();schedule();document.getElementById('reset-view').disabled=false;
}catch(e){fail(e.message.includes('WebGL')?'This browser cannot start 3D. Try Safari or Chrome with graphics enabled.':'The model could not load. Retry below; proposals still work.');console.error(e);}}
document.getElementById('reset-view').addEventListener('click',()=>{if(!controls)return;camera.position.copy(home);controls.target.copy(target);controls.update();schedule();});
document.getElementById('retry').addEventListener('click',()=>location.reload());
host.addEventListener('keydown',e=>{if(!camera||!state.ready||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const delta=camera.position.clone().sub(controls.target),s=new THREE.Spherical().setFromVector3(delta);s.theta+=(e.key==='ArrowLeft'?.15:e.key==='ArrowRight'?-.15:0);s.phi=THREE.MathUtils.clamp(s.phi+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0),.2,Math.PI/2-.02);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));controls.update();schedule();});
new ResizeObserver(resize).observe(host);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)schedule();},{rootMargin:'80px'}).observe(host);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});
window.addEventListener('pagehide',e=>{if(e.persisted)return;disposed=true;if(raf)cancelAnimationFrame(raf);renderer?.dispose();controls?.dispose();});window.addEventListener('pageshow',schedule);
// Local artwork, one texture and decal per placement. No uploads or tracking.
const designSlots=new Map();let armed=false,pointerStart=null,fileVersion=0;
const el=id=>document.getElementById(id),artStatus=text=>{el('art-status').textContent=text;};
const slot=()=>{const id=el('placement').value;if(!designSlots.has(id))designSlots.set(id,{brand:'',image:null,decal:null,canvas:null,texture:null});return designSlots.get(id);};
function paintArt(d){if(!d.canvas){d.canvas=document.createElement('canvas');d.canvas.width=1024;d.canvas.height=512;}const x=d.canvas.getContext('2d');x.clearRect(0,0,1024,512);if(d.image){const k=Math.min(960/d.image.width,440/d.image.height);x.drawImage(d.image,(1024-d.image.width*k)/2,(512-d.image.height*k)/2,d.image.width*k,d.image.height*k);}else{x.fillStyle='#eff9ff';let size=126;while(size>24){x.font='700 '+size+'px Arial';if(x.measureText(d.brand||'YOUR BRAND').width<960)break;size-=3;}x.textBaseline='middle';x.textAlign='center';x.fillText(d.brand||'YOUR BRAND',512,256);}if(!d.texture){d.texture=new THREE.CanvasTexture(d.canvas);d.texture.colorSpace=THREE.SRGBColorSpace;}d.texture.needsUpdate=true;schedule();return d.texture;}
function dropArt(d){if(!d.decal)return;scene.remove(d.decal);d.decal.geometry.dispose();d.decal.material.dispose();d.texture?.dispose();d.texture=null;d.decal=null;state.decals=[...designSlots.values()].filter(s=>s.decal).length;schedule();}
el('brand-name').addEventListener('input',()=>{const d=slot();d.brand=el('brand-name').value;if(d.decal&&el('art-rights').checked)paintArt(d);});
el('logo').addEventListener('change',async e=>{const file=e.target.files?.[0],d=slot(),v=++fileVersion;if(!file)return;let url;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2097152)throw Error('Use a PNG, JPG or WebP under 2 MB.');url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();if(!image.width||Math.max(image.width,image.height)>4096)throw Error('Use a logo up to 4096 pixels per side.');if(v!==fileVersion||d!==slot())return;const c=document.createElement('canvas'),s=Math.min(1,1024/Math.max(image.width,image.height));c.width=Math.round(image.width*s);c.height=Math.round(image.height*s);c.getContext('2d').drawImage(image,0,0,c.width,c.height);d.image=c;if(d.decal&&el('art-rights').checked)paintArt(d);artStatus('Logo ready. Click Place, then the intended body panel.');}catch(e){artStatus(e.message);}finally{if(url)URL.revokeObjectURL(url);e.target.value='';}});
el('place-logo').addEventListener('click',()=>{if(!state.ready)return;if(!el('art-rights').checked)return artStatus('Confirm artwork permission first.');armed=!armed;el('place-logo').textContent=armed?'Click the panel · Cancel':'Place on the car';artStatus(armed?'Click the intended body panel. Avoid windows, lights and vents.':'Placement cancelled.');});
el('art-rights').addEventListener('change',()=>{armed=false;el('place-logo').textContent='Place on the car';});
el('remove-logo').addEventListener('click',()=>{fileVersion++;const d=slot();dropArt(d);d.image=null;el('remove-logo').disabled=true;artStatus('Preview removed. Artwork was never uploaded.');});
document.addEventListener('gt3:placement',()=>{armed=false;fileVersion++;el('brand-name').value=slot().brand;el('remove-logo').disabled=!slot().decal;el('place-logo').textContent='Place on the car';});
function installPicking(){
 renderer.domElement.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY});
 renderer.domElement.addEventListener('pointerup',e=>{if(!armed||!el('art-rights').checked||!pointerStart||Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>7)return;const r=renderer.domElement.getBoundingClientRect(),p=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObject(model,true).find(h=>h.face&&!h.object.material.transparent&&!/glass|window|light/i.test(h.object.name));if(!hit)return artStatus('Choose an opaque body panel, not the background or glass.');const normal=hit.face.normal.clone().applyMatrix3(new THREE.Matrix3().getNormalMatrix(hit.object.matrixWorld)).normalize(),rotation=new THREE.Euler().setFromQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),normal));const geometry=new DecalGeometry(hit.object,hit.point,rotation,new THREE.Vector3(.65,.32,.12));if(!geometry.attributes.position.count){geometry.dispose();return artStatus('That area cannot hold the preview. Try a flatter panel.');}const d=slot();dropArt(d);d.decal=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:paintArt(d),transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4}));d.decal.renderOrder=3;scene.add(d.decal);armed=false;state.decals=[...designSlots.values()].filter(s=>s.decal).length;el('place-logo').textContent='Place on the car';el('remove-logo').disabled=false;artStatus('Logo placed on the 3D surface. Preview only, not installation artwork.');schedule();});
}
init();
