/**
 * LLM-Wiki Markdown Generator
 *
 * Auto-generates structured wiki markdown files based on
 * the knowledge map and detected gaps. Following Karpathy's
 * LLM-Wiki framework for organizing AI knowledge.
 */

import { KNOWLEDGE_DOMAINS, KNOWLEDGE_LINKS } from '../data/knowledgeGraph';

/**
 * Generate a full LLM-Wiki index page.
 */
export function generateWikiIndex(knowledgeMap) {
  const lines = [
    '# Knowledge Brain Wiki',
    '',
    '> Auto-generated knowledge map following the LLM-Wiki framework.',
    `> Last updated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Overview',
    '',
    `Total knowledge depth: **${(Object.values(knowledgeMap).reduce((a, d) => a + d.depth, 0) / Object.keys(knowledgeMap).length * 100).toFixed(0)}%**`,
    '',
    '## Domains',
    ''
  ];

  for (const [id, domain] of Object.entries(KNOWLEDGE_DOMAINS)) {
    const data = knowledgeMap[id] || { depth: 0, count: 0 };
    const bar = makeBar(data.depth);
    const status = data.depth > 0.6 ? 'strong' : data.depth > 0.3 ? 'developing' : 'gap';
    lines.push(`### ${domain.name} (${id})`);
    lines.push('');
    lines.push(`- **Depth:** ${bar} ${(data.depth * 100).toFixed(0)}% — *${status}*`);
    lines.push(`- **Documents:** ${data.count || 0}`);
    lines.push(`- **Scope:** ${domain.role}`);
    if (data.topics?.length) {
      lines.push(`- **Topics:** ${data.topics.slice(0, 8).join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## Knowledge Connections', '');
  for (const [from, to, desc] of KNOWLEDGE_LINKS) {
    lines.push(`- **${KNOWLEDGE_DOMAINS[from].name}** → **${KNOWLEDGE_DOMAINS[to].name}**: ${desc}`);
  }

  lines.push('', '---', '*Generated by BrainSNN Knowledge Brain*');
  return lines.join('\n');
}

/**
 * Generate a domain-specific wiki page.
 */
export function generateDomainPage(domainId, knowledgeMap, gaps = []) {
  const domain = KNOWLEDGE_DOMAINS[domainId];
  if (!domain) return '';
  const data = knowledgeMap[domainId] || { depth: 0, count: 0, topics: [], freshness: 0, coverage: 0 };
  const domainGaps = gaps.filter((g) => g.domain === domainId);

  const lines = [
    `# ${domain.name}`,
    '',
    `> Section: \`${domain.wikiSection}\``,
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Depth | ${(data.depth * 100).toFixed(0)}% |`,
    `| Freshness | ${(data.freshness * 100).toFixed(0)}% |`,
    `| Coverage | ${(data.coverage * 100).toFixed(0)}% |`,
    `| Documents | ${data.count} |`,
    '',
    '## Scope',
    '',
    domain.role,
    '',
    '## Key Topics',
    '',
    `Keywords: \`${domain.keywords.join('`, `')}\``,
    ''
  ];

  if (data.topics?.length) {
    lines.push('### Covered Topics', '');
    for (const topic of data.topics) {
      lines.push(`- ${topic}`);
    }
    lines.push('');
  }

  // Gaps and learning suggestions
  if (domainGaps.length) {
    lines.push('## Knowledge Gaps', '');
    for (const gap of domainGaps) {
      lines.push(`### ${gap.type.charAt(0).toUpperCase() + gap.type.slice(1)} (${gap.severity})`);
      lines.push('');
      lines.push(gap.message);
      lines.push('');
      lines.push(`**Action:** ${gap.suggestion}`);
      lines.push('');
    }
  }

  // Missing keywords (self-learning targets)
  const coveredText = (data.topics || []).join(' ').toLowerCase();
  const missing = domain.keywords.filter((kw) => !coveredText.includes(kw));
  if (missing.length) {
    lines.push('## Learning Targets', '');
    lines.push('Keywords not yet covered in your knowledge base:', '');
    for (const kw of missing) {
      lines.push(`- [ ] ${kw}`);
    }
    lines.push('');
  }

  // Cross-domain connections
  const connections = KNOWLEDGE_LINKS.filter(([from, to]) => from === domainId || to === domainId);
  if (connections.length) {
    lines.push('## Cross-Domain Connections', '');
    for (const [from, to, desc] of connections) {
      const other = from === domainId ? to : from;
      lines.push(`- **${KNOWLEDGE_DOMAINS[other]?.name || other}**: ${desc}`);
    }
    lines.push('');
  }

  lines.push('---', `*Generated by BrainSNN Knowledge Brain — ${new Date().toISOString().split('T')[0]}*`);
  return lines.join('\n');
}

/**
 * Generate all wiki files as a downloadable bundle.
 * Returns array of { filename, content } objects.
 */
export function generateWikiBundle(knowledgeMap, gaps = []) {
  const files = [];

  files.push({
    filename: 'index.md',
    content: generateWikiIndex(knowledgeMap)
  });

  for (const [id, domain] of Object.entries(KNOWLEDGE_DOMAINS)) {
    files.push({
      filename: `${domain.wikiSection}.md`,
      content: generateDomainPage(id, knowledgeMap, gaps)
    });
  }

  return files;
}

/**
 * Download wiki bundle as a zip-like concatenated file.
 * (Real zip would need a library; this creates a single markdown doc.)
 */
export function downloadWikiBundle(knowledgeMap, gaps = []) {
  const bundle = generateWikiBundle(knowledgeMap, gaps);
  const combined = bundle.map((f) => {
    return `<!-- FILE: ${f.filename} -->\n\n${f.content}\n\n`;
  }).join('\n---\n\n');

  const blob = new Blob([combined], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `knowledge-brain-wiki-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

function makeBar(value, width = 10) {
  const filled = Math.round(value * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}
