/**
 * LLM-Wiki Markdown Generator
 *
 * Auto-generates structured wiki markdown files based on
 * the knowledge map and detected gaps. Following Karpathy's
 * LLM-Wiki framework for organizing AI knowledge.
 */

import { KNOWLEDGE_DOMAINS, KNOWLEDGE_LINKS } from '../data/knowledgeGraph';

/**
 * Generate a full LLM-Wiki index page.
 */
export function generateWikiIndex(knowledgeMap) {
  const lines = [
    '# Knowledge Brain Wiki',
    '',
    '> Auto-generated knowledge map following the LLM-Wiki framework.',
    `> Last updated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Overview',
    '',
    `Total knowledge depth: **${(Object.values(knowledgeMap).reduce((a, d) => a + d.depth, 0) / Object.keys(knowledgeMap).length * 100).toFixed(0)}%**`,
    '',
    '## Domains',
    ''
  ];

  for (const [id, domain] of Object.entries(KNOWLEDGE_DOMAINS)) {
    const data = knowledgeMap[id] || { depth: 0, count: 0 };
    const bar = makeBar(data.depth);
    const status = data.depth > 0.6 ? 'strong' : data.depth > 0.3 ? 'developing' : 'gap';
    lines.push(`### ${domain.name} (${id})`);
    lines.push('');
    lines.push(`- **Depth:** ${bar} ${(data.depth * 100).toFixed(0)}% — *${status}*`);
    lines.push(`- **Documents:** ${data.count || 0}`);
    lines.push(`- **Scope:** ${domain.role}`);
    if (data.topics?.length) {
      lines.push(`- **Topics:** ${data.topics.slice(0, 8).join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## Knowledge Connections', '');
  for (const [from, to, desc] of KNOWLEDGE_LINKS) {
    lines.push(`- **${KNOWLEDGE_DOMAINS[from].name}** → **${KNOWLEDGE_DOMAINS[to].name}**: ${desc}`);
  }

  lines.push('', '---', '*Generated by BrainSNN Knowledge Brain*');
  return lines.join('\n');
}

/**
 * Generate a domain-specific wiki page.
 */
export function generateDomainPage(domainId, knowledgeMap, gaps = []) {
  const domain = KNOWLEDGE_DOMAINS[domainId];
  if (!domain) return '';
  const data = knowledgeMap[domainId] || { depth: 0, count: 0, topics: [], freshness: 0, coverage: 0 };
  const domainGaps = gaps.filter((g) => g.domain === domainId);

  const lines = [
    `# ${domain.name}`,
    '',
    `> Section: \`${domain.wikiSection}\``,
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Depth | ${(data.depth * 100).toFixed(0)}% |`,
    `| Freshness | ${(data.freshness * 100).toFixed(0)}% |`,
    `| Coverage | ${(data.coverage * 100).toFixed(0)}% |`,
    `| Documents | ${data.count} |`,
    '',
    '## Scope',
    '',
    domain.role,
    '',
    '## Key Topics',
    '',
    `Keywords: \`${domain.keywords.join('`, `')}\``,
    ''
  ];

  if (data.topics?.length) {
    lines.push('### Covered Topics', '');
    for (const topic of data.topics) {
      lines.push(`- ${topic}`);
    }
    lines.push('');
  }

  // Gaps and learning suggestions
  if (domainGaps.length) {
    lines.push('## Knowledge Gaps', '');
    for (const gap of domainGaps) {
      lines.push(`### ${gap.type.charAt(0).toUpperCase() + gap.type.slice(1)} (${gap.severity})`);
      lines.push('');
      lines.push(gap.message);
      lines.push('');
      lines.push(`**Action:** ${gap.suggestion}`);
      lines.push('');
    }
  }

  // Missing keywords (self-learning targets)
  const coveredText = (data.topics || []).join(' ').toLowerCase();
  const missing = domain.keywords.filter((kw) => !coveredText.includes(kw));
  if (missing.length) {
    lines.push('## Learning Targets', '');
    lines.push('Keywords not yet covered in your knowledge base:', '');
    for (const kw of missing) {
      lines.push(`- [ ] ${kw}`);
    }
    lines.push('');
  }

  // Cross-domain connections
  const connections = KNOWLEDGE_LINKS.filter(([from, to]) => from === domainId || to === domainId);
  if (connections.length) {
    lines.push('## Cross-Domain Connections', '');
    for (const [from, to, desc] of connections) {
      const other = from === domainId ? to : from;
      lines.push(`- **${KNOWLEDGE_DOMAINS[other]?.name || other}**: ${desc}`);
    }
    lines.push('');
  }

  lines.push('---', `*Generated by BrainSNN Knowledge Brain — ${new Date().toISOString().split('T')[0]}*`);
  return lines.join('\n');
}

/**
 * Generate all wiki files as a downloadable bundle.
 * Returns array of { filename, content } objects.
 */
export function generateWikiBundle(knowledgeMap, gaps = []) {
  const files = [];

  files.push({
    filename: 'index.md',
    content: generateWikiIndex(knowledgeMap)
  });

  for (const [id, domain] of Object.entries(KNOWLEDGE_DOMAINS)) {
    files.push({
      filename: `${domain.wikiSection}.md`,
      content: generateDomainPage(id, knowledgeMap, gaps)
    });
  }

  return files;
}

/**
 * Download wiki bundle as a zip-like concatenated file.
 * (Real zip would need a library; this creates a single markdown doc.)
 */
export function downloadWikiBundle(knowledgeMap, gaps = []) {
  const bundle = generateWikiBundle(knowledgeMap, gaps);
  const combined = bundle.map((f) => {
    return `<!-- FILE: ${f.filename} -->\n\n${f.content}\n\n`;
  }).join('\n---\n\n');

  const blob = new Blob([combined], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `knowledge-brain-wiki-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

function makeBar(value, width = 10) {
  const filled = Math.round(value * width);
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

// ---------- Graph-Insights wiki (Layer 101) ----------

/**
 * Render a graphify-style wiki bundle from a parsed code graph + its
 * detected communities + the analytics output of `analyzeGraph()`.
 *
 * Returns an array of { filename, content } objects:
 *   index.md            — overview, community list, top god-nodes,
 *                         surprising edges, suggested questions
 *   community-N.md      — one article per community (members, internal
 *                         edges, neighbor communities)
 */
export function generateGraphWikiBundle(graph, communities, analytics) {
  const files = [];
  const { nodes = [], edges = [], stats = {} } = graph || {};
  const commList = communities?.communities || [];
  const assignments = communities?.assignments || {};
  const nodeById = new Map(nodes.map((n) => [n.id, n]));

  // index.md ----------------------------------------------------------
  const indexLines = [
    '# Code Knowledge Graph',
    '',
    `> Auto-generated by Layer 101 (Graph Insights). ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Summary',
    '',
    `- **Files:** ${stats.totalFiles ?? '—'}`,
    `- **Symbols:** ${stats.totalSymbols ?? '—'}`,
    `- **External modules:** ${stats.totalExternals ?? 0}`,
    `- **Communities:** ${commList.length}`,
    `- **Modularity:** ${(communities?.modularity ?? 0).toFixed(3)}`,
    ''
  ];

  if (stats.provenance) {
    indexLines.push('### Edge confidence', '');
    indexLines.push('| Provenance | Edges |');
    indexLines.push('|---|---|');
    for (const [tag, count] of Object.entries(stats.provenance)) {
      indexLines.push(`| ${tag} | ${count} |`);
    }
    indexLines.push('');
  }

  if (commList.length) {
    indexLines.push('## Communities', '');
    commList.forEach((c, i) => {
      const slug = communitySlug(c, i);
      indexLines.push(`- [${c.label}](./${slug}.md) — ${c.members.length} member${c.members.length === 1 ? '' : 's'}`);
    });
    indexLines.push('');
  }

  if (analytics?.godNodes?.length) {
    indexLines.push('## God-nodes', '');
    indexLines.push('Nodes with high degree that bridge multiple communities.', '');
    for (const g of analytics.godNodes) {
      indexLines.push(`- **${g.label}** (${g.kind}) — degree ${g.degree}, ${g.communities} communities${g.path ? ` · \`${g.path}\`` : ''}`);
    }
    indexLines.push('');
  }

  if (analytics?.surprising?.length) {
    indexLines.push('## Surprising connections', '');
    for (const s of analytics.surprising) {
      indexLines.push(`- **${s.sourceLabel} ↔ ${s.targetLabel}** — score ${s.score.toFixed(2)} (${s.reasons.join(', ')})`);
    }
    indexLines.push('');
  }

  if (analytics?.questions?.length) {
    indexLines.push('## Suggested questions', '');
    for (const q of analytics.questions) {
      indexLines.push(`- _(${q.archetype})_ ${q.prompt}`);
    }
    indexLines.push('');
  }

  indexLines.push('---', '*Generated by BrainSNN Layer 101 — Graph Insights*');
  files.push({ filename: 'index.md', content: indexLines.join('\n') });

  // community-N.md ---------------------------------------------------
  commList.forEach((c, idx) => {
    const slug = communitySlug(c, idx);
    const memberSet = new Set(c.members);
    const internal = [];
    const outbound = new Map(); // otherCommunityId → count

    for (const e of edges) {
      const sIn = memberSet.has(e.source);
      const tIn = memberSet.has(e.target);
      if (sIn && tIn) {
        internal.push(e);
      } else if (sIn || tIn) {
        const otherId = sIn ? e.target : e.source;
        const otherComm = assignments[otherId];
        if (otherComm) outbound.set(otherComm, (outbound.get(otherComm) || 0) + 1);
      }
    }

    const lines = [
      `# ${c.label}`,
      '',
      `> Community \`${c.id}\` · ${c.members.length} members · ${internal.length} internal edge${internal.length === 1 ? '' : 's'}`,
      '',
      '## Members',
      ''
    ];

    const grouped = {};
    for (const mid of c.members) {
      const n = nodeById.get(mid);
      if (!n) continue;
      const k = n.kind || 'node';
      (grouped[k] ||= []).push(n);
    }
    for (const [kind, members] of Object.entries(grouped)) {
      lines.push(`### ${kind} (${members.length})`, '');
      for (const n of members) {
        const path = n.path ? ` — \`${n.path}\`${n.line ? `:${n.line}` : ''}` : '';
        lines.push(`- ${n.label}${path}`);
      }
      lines.push('');
    }

    if (outbound.size) {
      lines.push('## Connections to other communities', '');
      const ranked = Array.from(outbound.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10);
      for (const [otherId, count] of ranked) {
        const other = commList.find((x) => x.id === otherId);
        if (!other) continue;
        const otherSlug = communitySlug(other, commList.indexOf(other));
        lines.push(`- [${other.label}](./${otherSlug}.md) — ${count} edge${count === 1 ? '' : 's'}`);
      }
      lines.push('');
    }

    if (analytics?.godNodes?.length) {
      const touching = analytics.godNodes.filter((g) => {
        const cset = new Set();
        for (const e of edges) {
          if (e.source !== g.id && e.target !== g.id) continue;
          const other = e.source === g.id ? e.target : e.source;
          if (assignments[other]) cset.add(assignments[other]);
        }
        return cset.has(c.id);
      });
      if (touching.length) {
        lines.push('## God-nodes touching this community', '');
        for (const g of touching) {
          lines.push(`- **${g.label}** (degree ${g.degree}, spans ${g.communities} communities)`);
        }
        lines.push('');
      }
    }

    lines.push('---', `[← Back to index](./index.md)`);
    files.push({ filename: `${slug}.md`, content: lines.join('\n') });
  });

  return files;
}

function communitySlug(c, idx) {
  const safe = (c.label || c.id || `community-${idx}`)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || `community-${idx}`;
  return `community-${idx + 1}-${safe}`;
}

/**
 * Bundle the graph wiki as a single concatenated markdown blob and
 * trigger a download. Mirrors `downloadWikiBundle` for the existing
 * Knowledge Brain.
 */
export function downloadGraphWikiBundle(graph, communities, analytics) {
  const bundle = generateGraphWikiBundle(graph, communities, analytics);
  const combined = bundle.map((f) => `<!-- FILE: ${f.filename} -->\n\n${f.content}\n\n`).join('\n---\n\n');
  const blob = new Blob([combined], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `graph-insights-wiki-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
